import { openDB, get, put, getAll, STORES } from "./db/indexeddb.js";
import { dateId, clock, roundStart, roundEnd, roundToNearestFive, saved, minutesText } from "./modules/time.js";
import { getDay, saveDay, getState } from "./modules/workdays.js";
import { exportDB, importDB } from "./modules/backup.js";
import { getCurrentPosition, formatPosition } from "./modules/gps.js";
import { getOperationsForDay, getActiveOperation, startOperation, finishOperation } from "./modules/operations.js";
import { loadStores, searchStores, findNearestStore, storeLabel } from "./modules/stores.js";
import { reverseGeocode } from "./modules/reverse-geocode.js";
import { searchSavedPlaces, findNearestSavedPlace, savePlace, markPlaceUsed } from "./modules/places.js";
import { APP_CONFIG } from "./config/app-config.js";
import { setLanguage, getLanguage, t, locale, applyStaticTranslations } from "./i18n.js";

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentDay=null,currentMonth=new Date(),stores=[],selectedStore=null,selectedAddress=null,selectedSavedPlace=null,activeSettings=null;
const defaults={id:"main",workProfile:APP_CONFIG.defaultProfile,language:APP_CONFIG.defaultLanguage,defaultDriverName:"Andrzej Osowski",defaultTruckId:"",hourlyRate:225,overtimePercent:40,dailyMinutes:480,gpsRadius:120,updatedAt:Date.now()};
const dayTypeKeys={work:"workDay",vacation:"vacation",sick:"sick",egenmelding:"egenmelding",doctor:"doctor",holiday:"holiday",off:"off"};
const locationText={
  pl:{detect:"Ustal miejsce przez GPS",addressFound:"Adres ustalony",addressUnavailable:"Nie udało się ustalić adresu. Możesz wpisać miejsce ręcznie.",outsideStore:"Brak sklepu Europris w ustawionym promieniu. Wpisano bieżący adres.",saveName:"Nazwa firmy lub miejsca",save:"Zapisz miejsce",saved:"Miejsce zapisane",nearSaved:"Rozpoznano zapisane miejsce",saveError:"Nie udało się zapisać miejsca"},
  en:{detect:"Find location by GPS",addressFound:"Address found",addressUnavailable:"The address could not be determined. You can enter the location manually.",outsideStore:"No Europris store within the configured radius. Current address entered.",saveName:"Company or place name",save:"Save place",saved:"Place saved",nearSaved:"Saved place recognised",saveError:"Could not save place"},
  de:{detect:"Standort per GPS ermitteln",addressFound:"Adresse ermittelt",addressUnavailable:"Die Adresse konnte nicht ermittelt werden. Sie können den Ort manuell eingeben.",outsideStore:"Keine Europris-Filiale im eingestellten Radius. Aktuelle Adresse eingetragen.",saveName:"Firmen- oder Ortsname",save:"Ort speichern",saved:"Ort gespeichert",nearSaved:"Gespeicherter Ort erkannt",saveError:"Ort konnte nicht gespeichert werden"},
  no:{detect:"Finn sted med GPS",addressFound:"Adresse funnet",addressUnavailable:"Adressen kunne ikke fastslås. Du kan skrive inn stedet manuelt.",outsideStore:"Ingen Europris-butikk innenfor valgt radius. Gjeldende adresse er satt inn.",saveName:"Navn på firma eller sted",save:"Lagre sted",saved:"Sted lagret",nearSaved:"Lagret sted gjenkjent",saveError:"Kunne ikke lagre stedet"}
};
function lt(key){const l=getLanguage?.()||activeSettings?.language||"pl";return locationText[l]?.[key]||locationText.pl[key]||key;}
function toast(text){$("#toast").textContent=text;$("#toast").classList.remove("hidden");clearTimeout(toast.timer);toast.timer=setTimeout(()=>$("#toast").classList.add("hidden"),3000);}
function setView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='calendar')renderCalendar();if(name==='settings')loadSettings();}
function updateConnection(){$("#connectionStatus").textContent=navigator.onLine?t('online'):t('offline');}
async function ensureSettings(){let s=await get(STORES.settings,'main');if(!s){s=defaults;await put(STORES.settings,s);}activeSettings={...defaults,...s};setLanguage(activeSettings.language);return activeSettings;}
function profileDescription(p){return t(p==='europris'?'profileEuropris':'profileUniversal');}
function profileLabel(p){return p==='europris'?'Europris':t('universal');}
function operationType(type){return t(type==='unload'?'unload':'load');}
function applyLanguageUI(){setLanguage(activeSettings?.language||'pl');applyStaticTranslations();$("#savedPlaceName").placeholder=lt('saveName');$("#savePlaceButton").textContent=lt('save');updateConnection();applyProfileUI();renderHome();renderOperations();if($("#view-calendar").classList.contains('active'))renderCalendar();}
function applyProfileUI(){const profile=activeSettings?.workProfile||APP_CONFIG.defaultProfile,europris=profile==='europris';$("#activeProfileBadge").textContent=profileLabel(profile);$("#operationPlaceSearch").placeholder=t(europris?'europrisPlaceholder':'universalPlaceholder');$("#detectStoreButton").textContent=europris?t('detectStore'):lt('detect');$("#detectStoreButton").classList.remove('hidden');if(!europris){selectedStore=null;}else{$("#savePlacePanel").classList.add('hidden');selectedSavedPlace=null;}$("#storeSuggestions").classList.add('hidden');}
function renderHome(){const started=!!currentDay?.finalStartTime,ended=!!currentDay?.finalEndTime;$("#homeDriver").textContent=currentDay?.driverName||'—';$("#homeStart").textContent=currentDay?.finalStartTime||'—';$("#homeEnd").textContent=currentDay?.finalEndTime||'—';$("#homeTruck").textContent=currentDay?.truckId||'—';$("#homeTrailer").textContent=currentDay?.trailerNumber||'—';$("#homeNet").textContent=minutesText(currentDay?.netMinutes||0);$("#homeStartPosition").textContent=formatPosition(currentDay?.startPosition);$("#homeEndPosition").textContent=formatPosition(currentDay?.endPosition);$("#startWorkButton").disabled=started&&!ended;$("#stopWorkButton").disabled=!started||ended;$("#dayBadge").textContent=!started?t('notStarted'):ended?t('finished'):t('inProgress');$("#newUnloadButton").disabled=!started||ended;$("#newLoadButton").disabled=!started||ended;$("#detectStoreButton").disabled=!started||ended;applyProfileUI();}
async function refresh(){currentDay=await getDay();const state=await getState();renderHome();$("#lastSaved").textContent=state?.lastSavedAt||currentDay?.updatedAt?saved(state?.lastSavedAt||currentDay?.updatedAt):t('noSaves');await renderOperations();}
async function capturePosition(label){try{toast(t('gpsLoading',{label}));return await getCurrentPosition();}catch(error){toast(`${error.message} ${t('gpsNoData')}`);return null;}}
async function startWork(){const s=await ensureSettings(),now=new Date(),id=dateId(),position=await capturePosition(t('startWork'));currentDay=await saveDay({...currentDay,id,date:id,dayType:currentDay?.dayType??'work',driverName:currentDay?.driverName||s.defaultDriverName,truckId:currentDay?.truckId||s.defaultTruckId,detectedStartTime:clock(now),finalStartTime:roundStart(now),finalEndTime:null,startPosition:position??currentDay?.startPosition??null,manuallyAdjusted:false});toast(t('startSaved',{time:currentDay.finalStartTime}));await refresh();}
async function stopWork(){const active=await getActiveOperation(dateId());if(active)return toast(t('finishActiveFirst'));const now=new Date(),position=await capturePosition(t('stopWork'));currentDay=await saveDay({...currentDay,detectedEndTime:clock(now),finalEndTime:roundEnd(now),endPosition:position??currentDay?.endPosition??null,manuallyAdjusted:false});toast(t('endSaved',{time:currentDay.finalEndTime}));await refresh();}
function clearSelectedPlace(){selectedStore=null;selectedAddress=null;selectedSavedPlace=null;$("#selectedPlaceBox").classList.add('hidden');$("#selectedPlaceLabel").textContent='';$("#selectedPlaceAddress").textContent='';$("#savePlacePanel").classList.add('hidden');$("#savedPlaceName").value='';}
function chooseStore(store){selectedStore=store;selectedAddress=null;selectedSavedPlace=null;$("#operationPlaceSearch").value=storeLabel(store);$("#storeSuggestions").classList.add('hidden');$("#selectedPlaceLabel").textContent=storeLabel(store);$("#selectedPlaceAddress").textContent=store.address||'';$("#selectedPlaceBox").classList.remove('hidden');$("#savePlacePanel").classList.add('hidden');}
function chooseAddress(address,position){selectedStore=null;selectedSavedPlace=null;selectedAddress={...address,position};$("#operationPlaceSearch").value=address.formattedAddress;$("#storeSuggestions").classList.add('hidden');$("#selectedPlaceLabel").textContent=address.formattedAddress;$("#selectedPlaceAddress").textContent=address.localityLine||'';$("#selectedPlaceBox").classList.remove('hidden');$("#savePlacePanel").classList.toggle('hidden',activeSettings?.workProfile!=='universal');$("#savedPlaceName").value='';}
function chooseSavedPlace(place){selectedStore=null;selectedAddress=null;selectedSavedPlace=place;$("#operationPlaceSearch").value=place.name;$("#storeSuggestions").classList.add('hidden');$("#selectedPlaceLabel").textContent=place.name;$("#selectedPlaceAddress").textContent=place.address||'';$("#selectedPlaceBox").classList.remove('hidden');$("#savePlacePanel").classList.add('hidden');}
async function renderPlaceSuggestions(query){const box=$("#storeSuggestions");if(activeSettings?.workProfile==='europris'){const matches=searchStores(stores,query);if(!matches.length){box.classList.add('hidden');box.innerHTML='';return;}box.innerHTML=matches.map(s=>`<button type="button" data-store-number="${s.number}"><strong>${s.number} — ${s.name}</strong><span>${s.address||''}</span></button>`).join('');box.classList.remove('hidden');box.querySelectorAll('button').forEach(b=>b.onclick=()=>chooseStore(stores.find(s=>s.number===Number(b.dataset.storeNumber))));return;}const matches=await searchSavedPlaces(query);if(!matches.length){box.classList.add('hidden');box.innerHTML='';return;}box.innerHTML=matches.map(p=>`<button type="button" data-place-id="${p.id}"><strong>${p.name}</strong><span>${p.address||''}</span></button>`).join('');box.classList.remove('hidden');box.querySelectorAll('button').forEach(b=>b.onclick=()=>chooseSavedPlace(matches.find(p=>p.id===b.dataset.placeId)));}
async function detectLocation(){const position=await capturePosition(activeSettings?.workProfile==='europris'?t('detectStore'):lt('detect'));if(!position)return;if(activeSettings?.workProfile==='europris'&&stores.length){const nearest=findNearestStore(stores,position),radius=Number(activeSettings?.gpsRadius||120);if(nearest&&nearest.distance<=radius){chooseStore(nearest.store);return toast(t('detected',{store:storeLabel(nearest.store),distance:Math.round(nearest.distance)}));}}
  if(activeSettings?.workProfile==='universal'){const nearestSaved=await findNearestSavedPlace(position,Number(activeSettings?.gpsRadius||120));if(nearestSaved){const used=await markPlaceUsed(nearestSaved.place);chooseSavedPlace(used);return toast(`${lt('nearSaved')}: ${used.name} • ${Math.round(nearestSaved.distance)} m`);}}
  try{const address=await reverseGeocode(position,getLanguage?.()||activeSettings?.language||'pl');chooseAddress(address,position);toast(activeSettings?.workProfile==='europris'?lt('outsideStore'):lt('addressFound'));}catch(error){console.error(error);toast(lt('addressUnavailable'));}}
async function saveDetectedPlace(){if(!selectedAddress?.position)return toast(lt('saveError'));try{const place=await savePlace({name:$("#savedPlaceName").value,address:selectedAddress.formattedAddress,position:selectedAddress.position,locality:selectedAddress.locality,countryCode:selectedAddress.countryCode});chooseSavedPlace(place);toast(`${lt('saved')}: ${place.name}`);}catch(error){toast(error.message||lt('saveError'));}}
function selectedPlaceData(){const typed=$("#operationPlaceSearch").value.trim();if(selectedStore&&activeSettings?.workProfile==='europris')return{place:storeLabel(selectedStore),storeNumber:selectedStore.number,storeName:selectedStore.name,storeAddress:selectedStore.address,profile:'europris'};if(selectedSavedPlace&&typed===selectedSavedPlace.name)return{place:selectedSavedPlace.name,placeId:selectedSavedPlace.id,storeNumber:null,storeName:selectedSavedPlace.name,storeAddress:selectedSavedPlace.address||null,locality:selectedSavedPlace.locality||null,countryCode:selectedSavedPlace.countryCode||null,profile:'universal'};if(selectedAddress&&typed===selectedAddress.formattedAddress)return{place:typed,storeNumber:null,storeName:null,storeAddress:selectedAddress.formattedAddress,locality:selectedAddress.locality||null,countryCode:selectedAddress.countryCode||null,profile:activeSettings?.workProfile||'universal'};if(typed)return{place:typed,storeNumber:null,storeName:null,storeAddress:null,profile:activeSettings?.workProfile||'universal'};return null;}
async function startSelectedOperation(type){const place=selectedPlaceData();if(!place)return toast(t('selectPlace'));if(await getActiveOperation(dateId()))return toast(t('oneOperation'));const now=new Date(),position=selectedSavedPlace?.position||selectedAddress?.position||await capturePosition(operationType(type));await startOperation({workdayId:dateId(),type,...place,detectedStartTime:clock(now),startTime:roundToNearestFive(now),position});if(selectedSavedPlace)await markPlaceUsed(selectedSavedPlace);toast(t('operationStarted',{type:operationType(type),time:roundToNearestFive(now)}));clearSelectedPlace();$("#operationPlaceSearch").value='';await renderOperations();}
function openFinishForm(active){$("#finishOperationForm").classList.remove('hidden');$("#finishEmptyPalletsLabel").classList.toggle('hidden',active.type==='load');$("#finishPallets").value='';$("#finishEmptyPallets").value='';$("#finishNotes").value='';$("#finishPallets").focus();}
async function confirmFinishOperation(){const active=await getActiveOperation(dateId());if(!active)return;if($("#finishPallets").value==='')return toast(t('enterQuantity'));const now=new Date();try{await finishOperation(active.id,{detectedEndTime:clock(now),endTime:roundToNearestFive(now),pallets:$("#finishPallets").value,emptyPallets:$("#finishEmptyPallets").value,notes:$("#finishNotes").value.trim()});$("#finishOperationForm").classList.add('hidden');toast(t('operationFinished',{time:roundToNearestFive(now)}));await renderOperations();}catch(error){toast(error.message);}}
async function renderOperations(){const items=await getOperationsForDay(dateId()),active=items.find(i=>!i.endTime);$("#activeOperationBox").classList.toggle('hidden',!active);$("#operationSelector").classList.toggle('hidden',!!active);if(active){$("#activeOperationTitle").textContent=`${operationType(active.type)}: ${active.place}`;$("#activeOperationTime").textContent=t('from',{time:active.startTime});}else $("#finishOperationForm").classList.add('hidden');$("#todayOperations").innerHTML=items.length?items.map(i=>`<div class="timeline-item"><strong>${operationType(i.type)}: ${i.place}</strong><span>${i.startTime} – ${i.endTime||t('lasting')}${i.endTime?` • ${t('amount')}: ${i.pallets??0}`:''}${i.type==='unload'&&i.endTime?` • ${t('empty')}: ${i.emptyPallets??0}`:''}</span>${i.storeAddress&&i.storeAddress!==i.place?`<span>${i.storeAddress}</span>`:''}${i.notes?`<span>${i.notes}</span>`:''}</div>`).join(''):`<p class="muted">${t('noOperations')}</p>`;}
async function loadDayForm(id=dateId()){const day=await getDay(id),s=await ensureSettings();$("#workDate").value=id;$("#dayType").value=day?.dayType??'work';$("#driverName").value=day?.driverName??s.defaultDriverName;$("#startTime").value=day?.finalStartTime??'';$("#endTime").value=day?.finalEndTime??'';$("#truckId").value=day?.truckId??s.defaultTruckId;$("#trailerNumber").value=day?.trailerNumber??'';$("#breakMinutes").value=day?.breakMinutes??0;$("#notes").value=day?.notes??'';$("#dayFormTitle").textContent=new Intl.DateTimeFormat(locale(),{dateStyle:'full'}).format(new Date(`${id}T12:00:00`));setView('day');}
async function saveDayForm(event){event.preventDefault();const trailer=$("#trailerNumber").value.trim();if(trailer&&(Number(trailer)<1||Number(trailer)>999))return toast(t('trailerError'));const id=$("#workDate").value;await saveDay({...await getDay(id),id,date:id,dayType:$("#dayType").value,driverName:$("#driverName").value.trim(),finalStartTime:$("#startTime").value||null,finalEndTime:$("#endTime").value||null,truckId:$("#truckId").value.trim(),trailerNumber:trailer?Number(trailer):null,breakMinutes:Number($("#breakMinutes").value||0),notes:$("#notes").value.trim(),manuallyAdjusted:true});toast(t('daySaved'));await refresh();setView('calendar');}
async function renderCalendar(){const s=await ensureSettings(),workdays=await getAll(STORES.workdays),year=currentMonth.getFullYear(),month=currentMonth.getMonth(),rows=$("#monthRows");rows.innerHTML='';$("#calendarTitle").textContent=new Intl.DateTimeFormat(locale(),{month:'long',year:'numeric'}).format(currentMonth);let total=0,days=0,overtime=0,gross=0;for(let n=1;n<=new Date(year,month+1,0).getDate();n++){const id=`${year}-${String(month+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`,day=workdays.find(x=>x.id===id),net=day?.netMinutes||0,extra=Math.max(0,net-s.dailyMinutes);if(day?.dayType==='work'&&net>0)days++;total+=net;overtime+=extra;gross+=(Math.max(0,net-extra)/60)*s.hourlyRate+(extra/60)*s.hourlyRate*(1+s.overtimePercent/100);const date=new Date(year,month,n),row=document.createElement('div');row.className=`day-row ${day?'':'empty-day'}`;row.innerHTML=`<button type="button" data-date="${id}"><div class="day-date"><strong>${String(n).padStart(2,'0')}</strong><span>${new Intl.DateTimeFormat(locale(),{weekday:'short'}).format(date)}</span></div><div class="day-details"><strong>${day?t(dayTypeKeys[day.dayType]||'workDay'):t('noEntry')}</strong><span>${day?.finalStartTime||'—'} – ${day?.finalEndTime||'—'} • ${day?.truckId||t('noTruck')}</span></div><div class="day-hours">${minutesText(net)}</div></button>`;rows.appendChild(row);}rows.querySelectorAll('button').forEach(b=>b.onclick=()=>loadDayForm(b.dataset.date));$("#totalHours").textContent=minutesText(total);$("#totalDays").textContent=String(days);$("#totalOvertime").textContent=minutesText(overtime);$("#totalGross").textContent=`${gross.toFixed(0)} NOK`;}
async function loadSettings(){const s=await ensureSettings();$("#language").value=s.language;$("#workProfile").value=s.workProfile;$("#profileDescription").textContent=profileDescription(s.workProfile);$("#defaultDriverName").value=s.defaultDriverName;$("#defaultTruckId").value=s.defaultTruckId;$("#hourlyRate").value=s.hourlyRate;$("#overtimePercent").value=s.overtimePercent;$("#dailyMinutes").value=s.dailyMinutes;$("#gpsRadius").value=s.gpsRadius;}
async function saveSettings(event){event.preventDefault();await put(STORES.settings,{id:'main',workProfile:$("#workProfile").value,language:$("#language").value,defaultDriverName:$("#defaultDriverName").value.trim(),defaultTruckId:$("#defaultTruckId").value.trim(),hourlyRate:Number($("#hourlyRate").value||0),overtimePercent:Number($("#overtimePercent").value||0),dailyMinutes:Number($("#dailyMinutes").value||0),gpsRadius:Math.min(120,Math.max(20,Number($("#gpsRadius").value||120))),updatedAt:Date.now()});await ensureSettings();clearSelectedPlace();$("#operationPlaceSearch").value='';applyLanguageUI();$("#profileDescription").textContent=profileDescription(activeSettings.workProfile);toast(t('settingsSaved'));await refresh();}
function bindEvents(){$$('.nav-button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$("#startWorkButton").onclick=startWork;$("#stopWorkButton").onclick=stopWork;$("#editTodayButton").onclick=()=>loadDayForm();$("#operationPlaceSearch").oninput=e=>{selectedStore=null;selectedAddress=null;selectedSavedPlace=null;$("#selectedPlaceBox").classList.add('hidden');$("#savePlacePanel").classList.add('hidden');renderPlaceSuggestions(e.target.value);};$("#detectStoreButton").onclick=detectLocation;$("#savePlaceButton").onclick=saveDetectedPlace;$("#newUnloadButton").onclick=()=>startSelectedOperation('unload');$("#newLoadButton").onclick=()=>startSelectedOperation('load');$("#finishOperationButton").onclick=async()=>{const a=await getActiveOperation(dateId());if(a)openFinishForm(a);};$("#confirmFinishOperationButton").onclick=confirmFinishOperation;$("#cancelFinishOperationButton").onclick=()=>$("#finishOperationForm").classList.add('hidden');$("#cancelEditButton").onclick=()=>setView('home');$("#dayForm").onsubmit=saveDayForm;$("#settingsForm").onsubmit=saveSettings;$("#language").onchange=e=>{setLanguage(e.target.value);applyStaticTranslations();applyLanguageUI();$("#profileDescription").textContent=profileDescription($("#workProfile").value);};$("#workProfile").onchange=e=>$("#profileDescription").textContent=profileDescription(e.target.value);$("#previousMonth").onclick=()=>{currentMonth=new Date(currentMonth.getFullYear(),currentMonth.getMonth()-1,1);renderCalendar();};$("#nextMonth").onclick=()=>{currentMonth=new Date(currentMonth.getFullYear(),currentMonth.getMonth()+1,1);renderCalendar();};$("#exportButton").onclick=exportDB;$("#importInput").onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{await importDB(file);await ensureSettings();applyLanguageUI();toast(t('backupImported'));await refresh();await renderCalendar();}catch(error){toast(error.message);}e.target.value='';};addEventListener('online',updateConnection);addEventListener('offline',updateConnection);}
async function boot(){bindEvents();await openDB();await ensureSettings();applyStaticTranslations();applyLanguageUI();$("#appVersion").textContent=`v${APP_CONFIG.version}`;if(activeSettings.workProfile==='europris'){try{stores=await loadStores();}catch(error){console.error(error);toast(t('storesOffline'));}}applyProfileUI();await refresh();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(console.error);}
boot().catch(error=>{console.error(error);toast(t('startupError'));});