import { get, put, STORES } from "./db/indexeddb.js";
import { getActiveOperation, getOperationsForDay } from "./modules/operations.js";
import { dateId, clock, roundToNearestFive } from "./modules/time.js";

const $=s=>document.querySelector(s);
const MAX_ITEMS=5;
const UNIT_LABELS={pallets:"palety",cartons:"kartony",pieces:"sztuki",kg:"kg",tonnes:"tony",m3:"m³",litres:"litry"};
const UNIT_OPTIONS=Object.entries(UNIT_LABELS).map(([v,l])=>`<option value="${v}">${l}</option>`).join("");
function toast(text){const el=$("#toast");if(!el)return;el.textContent=text;el.classList.remove("hidden");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add("hidden"),2600);}
function ensureStyle(){if($("#cargoItemsStyle"))return;const s=document.createElement("style");s.id="cargoItemsStyle";s.textContent=`.cargo-items-box{display:grid;gap:8px;margin:8px 0}.cargo-item-row,.cargo-empty-row{display:grid;grid-template-columns:minmax(0,1fr) 92px 36px;gap:7px;align-items:end;padding:8px;border:1px solid var(--line);border-radius:12px;background:var(--card)}.cargo-item-row label,.cargo-empty-row label{margin:0}.cargo-item-row input,.cargo-item-row select,.cargo-empty-row input{margin:3px 0 0}.cargo-remove{height:42px;padding:0;font-size:1.1rem}.cargo-add{margin:2px 0 8px}.cargo-empty-unit{height:42px;display:flex;align-items:center;padding:0 10px;border:1px solid var(--line);border-radius:9px;background:var(--surface,#fff);font-size:.9rem}.cargo-empty-spacer{width:36px}.cargo-summary{display:block;margin-top:4px;font-weight:700;color:var(--text)}#finishPalletsLegacy,#finishEmptyPalletsLabel{display:none!important}@media(max-width:430px){.cargo-item-row,.cargo-empty-row{grid-template-columns:1fr 84px 36px}}`;document.head.appendChild(s);}
async function defaultUnit(){try{return (await get(STORES.appState,"transport-profile"))?.cargoUnit||"pallets";}catch{return "pallets";}}
function rowHtml(){return `<div class="cargo-item-row" data-cargo-row><label>Ilość<input data-cargo-qty type="number" min="0" step="0.01" inputmode="decimal" placeholder="0"></label><label>Jednostka<select data-cargo-unit>${UNIT_OPTIONS}</select></label><button type="button" class="cargo-remove" data-cargo-remove aria-label="Usuń">×</button></div>`;}
function hideLegacyFields(){const oldQty=$("#finishPallets")?.closest("label");const oldEmpty=$("#finishEmptyPalletsLabel");if(oldQty){oldQty.id="finishPalletsLegacy";oldQty.classList.add("hidden");oldQty.style.display="none";}if(oldEmpty){oldEmpty.classList.add("hidden");oldEmpty.style.display="none";}}
async function prepareForm(){const form=$("#finishOperationForm");if(!form||form.classList.contains("hidden"))return;ensureStyle();hideLegacyFields();if($("#cargoItemsBox"))return;const unit=await defaultUnit();const box=document.createElement("div");box.id="cargoItemsBox";box.className="cargo-items-box";box.innerHTML=`<strong>Pozycje ładunku</strong><div id="cargoRows"></div><div class="cargo-empty-row"><label>Puste palety<input id="cargoEmptyPallets" type="number" min="0" step="1" inputmode="numeric" placeholder="0"></label><div class="cargo-empty-unit">palety</div><div class="cargo-empty-spacer"></div></div><button id="cargoAddButton" class="cargo-add" type="button">+ Dodaj kolejną pozycję</button><small class="muted">Możesz zapisać do 5 rodzajów ładunku w jednej operacji.</small>`;const notes=$("#finishNotes")?.closest("label");form.insertBefore(box,notes||form.firstChild);addRow(unit);$("#cargoAddButton").onclick=()=>addRow(unit);}
function addRow(unit){const rows=$("#cargoRows");if(!rows||rows.children.length>=MAX_ITEMS)return;rows.insertAdjacentHTML("beforeend",rowHtml());const row=rows.lastElementChild;row.querySelector("[data-cargo-unit]").value=unit;row.querySelector("[data-cargo-remove]").onclick=()=>{if(rows.children.length>1){row.remove();if($("#cargoAddButton"))$("#cargoAddButton").disabled=false;}};row.querySelector("[data-cargo-qty]").focus();if(rows.children.length>=MAX_ITEMS)$("#cargoAddButton").disabled=true;}
function collectItems(){return [...document.querySelectorAll("[data-cargo-row]")].map(row=>({quantity:Number(row.querySelector("[data-cargo-qty]").value),unit:row.querySelector("[data-cargo-unit]").value})).filter(x=>Number.isFinite(x.quantity)&&x.quantity>0).slice(0,MAX_ITEMS);}
async function saveCargoFinish(event){const button=event.target.closest("#confirmFinishOperationButton");if(!button||!$("#cargoItemsBox"))return;event.preventDefault();event.stopImmediatePropagation();const items=collectItems();if(!items.length)return toast("Wpisz przynajmniej jedną ilość ładunku.");const active=await getActiveOperation(dateId());if(!active)return toast("Brak aktywnej operacji.");const emptyRaw=$("#cargoEmptyPallets")?.value??"";const emptyPallets=emptyRaw===""?0:Math.max(0,Number(emptyRaw)||0);const now=new Date();const updated={...active,endTime:roundToNearestFive(now),detectedEndTime:clock(now),cargoItems:items,pallets:items[0].quantity,emptyPallets,notes:$("#finishNotes")?.value.trim()||"",endedAt:Date.now(),updatedAt:Date.now()};await put(STORES.operations,updated);toast("Operacja zakończona i zapisana.");setTimeout(()=>location.reload(),450);}
async function enhanceToday(){const box=$("#todayOperations");if(!box)return;const items=await getOperationsForDay(dateId());const rows=[...box.querySelectorAll(".timeline-item")];const ordered=[...items].sort((a,b)=>(Number(b.endedAt||0)-Number(a.endedAt||0))||String(b.startTime||"").localeCompare(String(a.startTime||"")));ordered.forEach((op,index)=>{const row=rows[index];if(!row||row.querySelector(".cargo-summary"))return;const parts=[];if(op.cargoItems?.length)parts.push(op.cargoItems.map(x=>`${x.quantity} ${UNIT_LABELS[x.unit]||x.unit}`).join(" • "));if(Number(op.emptyPallets)>0)parts.push(`puste palety: ${op.emptyPallets}`);if(!parts.length)return;const span=document.createElement("span");span.className="cargo-summary";span.textContent=parts.join(" • ");row.appendChild(span);});}
function boot(){ensureStyle();document.addEventListener("click",saveCargoFinish,true);new MutationObserver(()=>{hideLegacyFields();prepareForm().catch(console.error);enhanceToday().catch(console.error);}).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["class","style"]});document.addEventListener("dashboard-view-opened",e=>{if(e.detail==="operations")setTimeout(()=>{hideLegacyFields();enhanceToday().catch(console.error);},80);});}
boot();