import "./operation-controls-fix.js";
import "./places-manager.js";
import "./innovation-pack.js";
import "./workday-layout.js";
import "./workday-odometer.js";
import "./workday-odometer-finish.js";
import "./workday-action-state.js";
import "./app-information.js";
import "./journal-archive.js";
import "./archive-month-selector.js";
import "./timeline-operation-times.js";
import "./life-trailer-timeline.js";
import "./dynamic-view-activation-fix.js";
import "./transport-profile.js";
import "./data-health.js";
import "./cargo-items.js";
import "./monthly-pay-summary.js";
import { get, STORES } from "./db/indexeddb.js";
import { getDay } from "./modules/workdays.js";
import { dateId } from "./modules/time.js";

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const TEXT={
pl:{workday:"Aktywny dzień pracy",workdayHint:"Czas, pojazd, naczepa i zdarzenia zestawu",operations:"Załadunki i rozładunki",operationsHint:"Rozpoczęcie, zakończenie i edycja operacji",payments:"Rozliczenie / stawki",paymentsHint:"Stawki, nadgodziny i godziny nocne",history:"Archiwum",historyHint:"Wyszukiwanie po całej historii",vehicles:"Pojazdy i naczepy",vehiclesHint:"Historia według numeru rejestracyjnego",stats:"Statystyki",statsHint:"Kilometry, operacje i najczęstsze miejsca",life:"Oś życia kierowcy",lifeHint:"Dni pracy z rozwijaną pełną historią",transport:"Konfiguracja transportu",transportHint:"Typ pojazdu, zabudowy i jednostka ładunku",places:"Miejsca",placesHint:"Zapisane adresy i lokalizacje GPS",settings:"Ustawienia",settingsHint:"Profil, przewoźnik i kopia danych",produced:"Wyprodukował Rumcajs",title:"Osobisty dziennik kierowcy",profile:"Profil",truck:"Samochód",trailer:"Naczepa",since:"Praca od",universal:"Uniwersalny",startWork:"Rozpocznij pracę",stopWork:"Zakończ pracę",notStarted:"Nie rozpoczęto",finished:"Zakończono"},
en:{workday:"Active workday",workdayHint:"Time, vehicle, trailer and combination events",operations:"Loading and unloading",operationsHint:"Start, finish and edit operations",payments:"Payments / rates",paymentsHint:"Rates, overtime and night work",history:"Archive",historyHint:"Search the full journal",vehicles:"Vehicles and trailers",vehiclesHint:"History by registration number",stats:"Statistics",statsHint:"Distance, operations and top places",life:"Driver timeline",lifeHint:"Workdays with expandable full history",transport:"Transport configuration",transportHint:"Vehicle, body and cargo unit",places:"Places",placesHint:"Saved addresses and GPS locations",settings:"Settings",settingsHint:"Profile, carrier and backup",produced:"Produced by Rumcajs",title:"Driver's personal journal",profile:"Profile",truck:"Vehicle",trailer:"Trailer",since:"Working since",universal:"Universal",startWork:"Start work",stopWork:"Finish work",notStarted:"Not started",finished:"Finished"},
de:{workday:"Aktiver Arbeitstag",workdayHint:"Zeit, Fahrzeug, Auflieger und Gespannereignisse",operations:"Be- und Entladungen",operationsHint:"Vorgänge starten, beenden und bearbeiten",payments:"Abrechnung / Tarife",paymentsHint:"Tarife, Überstunden und Nachtarbeit",history:"Archiv",historyHint:"Im gesamten Fahrertagebuch suchen",vehicles:"Fahrzeuge und Auflieger",vehiclesHint:"Verlauf nach Kennzeichen",stats:"Statistiken",statsHint:"Kilometer, Vorgänge und häufigste Orte",life:"Fahrer-Zeitleiste",lifeHint:"Arbeitstage mit ausklappbarer Gesamthistorie",transport:"Transportkonfiguration",transportHint:"Fahrzeugtyp, Aufbau und Ladeeinheit",places:"Orte",placesHint:"Gespeicherte Adressen und GPS-Standorte",settings:"Einstellungen",settingsHint:"Profil, Spediteur und Datensicherung",produced:"Erstellt von Rumcajs",title:"Persönliches Fahrertagebuch",profile:"Profil",truck:"Fahrzeug",trailer:"Auflieger",since:"Arbeit seit",universal:"Universal",startWork:"Arbeit beginnen",stopWork:"Arbeit beenden",notStarted:"Nicht begonnen",finished:"Beendet"},
no:{workday:"Aktiv arbeidsdag",workdayHint:"Tid, kjøretøy, tilhenger og hendelser for vogntoget",operations:"Lasting og lossing",operationsHint:"Start, avslutt og rediger operasjoner",payments:"Oppgjør / satser",paymentsHint:"Satser, overtid og nattarbeid",history:"Arkiv",historyHint:"Søk i hele kjøredagboken",vehicles:"Kjøretøy og tilhengere",vehiclesHint:"Historikk etter registreringsnummer",stats:"Statistikk",statsHint:"Kilometer, operasjoner og mest brukte steder",life:"Sjåførens tidslinje",lifeHint:"Arbeidsdager med utvidbar full historikk",transport:"Transportoppsett",transportHint:"Kjøretøytype, påbygg og lastenhet",places:"Steder",placesHint:"Lagrede adresser og GPS-posisjoner",settings:"Innstillinger",settingsHint:"Profil, transportør og sikkerhetskopi",produced:"Laget av Rumcajs",title:"Personlig kjøredagbok",profile:"Profil",truck:"Kjøretøy",trailer:"Tilhenger",since:"Arbeid siden",universal:"Universell",startWork:"Start arbeid",stopWork:"Avslutt arbeid",notStarted:"Ikke startet",finished:"Avsluttet"}
};
const ui=()=>TEXT[document.documentElement.lang||"pl"]||TEXT.pl;
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'});document.dispatchEvent(new CustomEvent('dashboard-view-opened',{detail:name}));}
function openModule(name){if(name==='settings'){document.querySelector('.nav-button[data-view="settings"]')?.click();setTimeout(()=>document.dispatchEvent(new CustomEvent('dashboard-view-opened',{detail:'settings'})),0);return;}if(name==='payments'){$('#openPaymentsButton')?.click();setTimeout(()=>document.dispatchEvent(new CustomEvent('dashboard-view-opened',{detail:'payments'})),0);return;}showView(name);}
const tile=(icon,title,hint,target)=>`<button class="dashboard-tile dashboard-${target}" type="button" data-dashboard-view="${target}"><span class="dashboard-tile-icon">${icon}</span><div><strong>${title}</strong><span>${hint}</span></div></button>`;
async function renderDashboard(){const home=$('#view-home');if(!home)return;const t=ui();let settings=null,day=null;try{[settings,day]=await Promise.all([get(STORES.settings,'main'),getDay(dateId())]);}catch(error){console.error(error);}const profile=settings?.workProfile==='europris'?'Europris':t.universal,trailer=day?.trailerId||day?.trailerNumber||'Solo',started=!!day?.finalStartTime,ended=!!day?.finalEndTime;home.innerHTML=`<div class="brand-strip"><div class="brand-rumcajs"><img src="./assets/rumcajs-logo.svg" alt="Rumcajs"><span>${t.produced}</span></div><div class="brand-title"><strong>${t.title}</strong><small id="dashboardVersion"></small></div></div><div class="dashboard-status"><div><span>${t.profile}</span><strong>${profile}</strong></div><div><span>${t.truck}</span><strong>${day?.truckId||'—'}</strong></div><div><span>${t.trailer}</span><strong>${trailer}</strong></div><div><span>${t.since}</span><strong>${day?.finalStartTime||'—'}</strong></div><button class="dashboard-status-action dashboard-start-action" type="button" data-work-action="start" ${started&&!ended?'disabled':''}><span>${t.startWork}</span><strong>${day?.finalStartTime||t.notStarted}</strong></button><button class="dashboard-status-action dashboard-stop-action" type="button" data-work-action="stop" ${!started||ended?'disabled':''}><span>${t.stopWork}</span><strong>${day?.finalEndTime||t.finished}</strong></button></div><div class="dashboard-grid">${tile('🕒',t.workday,t.workdayHint,'workday')}${tile('📦',t.operations,t.operationsHint,'operations')}${tile('📖',t.history,t.historyHint,'history')}${tile('🧭',t.life,t.lifeHint,'life')}${tile('📊',t.stats,t.statsHint,'stats')}${tile('🚛',t.vehicles,t.vehiclesHint,'vehicles')}${settings?.workProfile==='universal'?tile('⚙️',t.transport,t.transportHint,'transport'):''}${tile('💰',t.payments,t.paymentsHint,'payments')}${tile('📍',t.places,t.placesHint,'places')}${tile('⚙️',t.settings,t.settingsHint,'settings')}</div>`;$('#dashboardVersion').textContent=$('#appVersion')?.textContent||'';document.dispatchEvent(new CustomEvent('dashboard-view-opened',{detail:'home'}));}
function refreshDashboardAfterAction(){[500,1500,3500,7000].forEach(delay=>setTimeout(()=>{if($('#view-home')?.classList.contains('active'))renderDashboard().catch(console.error);},delay));}
function boot(){renderDashboard().catch(console.error);document.addEventListener('click',e=>{const action=e.target.closest('[data-work-action]');if(action){e.preventDefault();if(action.disabled)return;const source=action.dataset.workAction==='start'?$('#startWorkButton'):$('#stopWorkButton');source?.click();refreshDashboardAfterAction();return;}const m=e.target.closest('[data-dashboard-view]');if(m){e.preventDefault();openModule(m.dataset.dashboardView);return;}if(e.target.closest('[data-open-settings]'))openModule('settings');if(e.target.closest('.module-back'))showView('home');});document.querySelector('.nav-button[data-view="home"]')?.addEventListener('click',()=>setTimeout(()=>renderDashboard().catch(console.error),0));document.addEventListener('visibilitychange',()=>{if(!document.hidden&&$('#view-home')?.classList.contains('active'))renderDashboard().catch(console.error);});document.addEventListener('profile-changed',()=>renderDashboard().catch(console.error));}
boot();