import { get, STORES } from "./db/indexeddb.js";
import { getDay } from "./modules/workdays.js";
import { dateId } from "./modules/time.js";

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];

const TEXT={
 pl:{workday:"Aktywny dzień pracy",workdayHint:"Czas, pojazd, naczepa i zdarzenia zestawu",operations:"Załadunki i rozładunki",operationsHint:"Rozpoczęcie, zakończenie i edycja operacji",payments:"Rozliczenie / stawki",paymentsHint:"Stawki, nadgodziny i godziny nocne",history:"Historia",historyHint:"Wyszukiwanie zapisów kierowcy",vehicles:"Pojazdy i zestawy",vehiclesHint:"Samochody, naczepy i przebiegi",places:"Miejsca",placesHint:"Zapisane adresy i lokalizacje GPS",settings:"Ustawienia",settingsHint:"Profil, przewoźnik i kopia danych",produced:"Wyprodukował Rumcajs",title:"Osobisty dziennik kierowcy",profile:"Profil",truck:"Samochód",trailer:"Naczepa",since:"Praca od",back:"Wróć"},
 en:{workday:"Active workday",workdayHint:"Time, vehicle, trailer and combination events",operations:"Loading and unloading",operationsHint:"Start, finish and edit operations",payments:"Payments / rates",paymentsHint:"Rates, overtime and night work",history:"History",historyHint:"Search the driver's records",vehicles:"Vehicles and combinations",vehiclesHint:"Vehicles, trailers and mileage",places:"Places",placesHint:"Saved addresses and GPS locations",settings:"Settings",settingsHint:"Profile, carrier and backup",produced:"Produced by Rumcajs",title:"Driver's personal journal",profile:"Profile",truck:"Vehicle",trailer:"Trailer",since:"Working since",back:"Back"},
 de:{workday:"Aktiver Arbeitstag",workdayHint:"Zeit, Fahrzeug, Anhänger und Gespannereignisse",operations:"Be- und Entladung",operationsHint:"Vorgänge starten, beenden und bearbeiten",payments:"Abrechnung / Sätze",paymentsHint:"Sätze, Überstunden und Nachtarbeit",history:"Verlauf",historyHint:"Fahreraufzeichnungen durchsuchen",vehicles:"Fahrzeuge und Gespanne",vehiclesHint:"Fahrzeuge, Anhänger und Kilometerstände",places:"Orte",placesHint:"Gespeicherte Adressen und GPS-Orte",settings:"Einstellungen",settingsHint:"Profil, Frachtführer und Sicherung",produced:"Produziert von Rumcajs",title:"Persönliches Fahrertagebuch",profile:"Profil",truck:"Fahrzeug",trailer:"Anhänger",since:"Arbeit seit",back:"Zurück"},
 no:{workday:"Aktiv arbeidsdag",workdayHint:"Tid, kjøretøy, henger og hendelser",operations:"Lasting og lossing",operationsHint:"Start, avslutt og rediger operasjoner",payments:"Oppgjør / satser",paymentsHint:"Satser, overtid og nattarbeid",history:"Historikk",historyHint:"Søk i førerens registreringer",vehicles:"Kjøretøy og vogntog",vehiclesHint:"Biler, hengere og kilometerstand",places:"Steder",placesHint:"Lagrede adresser og GPS-steder",settings:"Innstillinger",settingsHint:"Profil, transportør og sikkerhetskopi",produced:"Produsert av Rumcajs",title:"Førerens personlige dagbok",profile:"Profil",truck:"Bil",trailer:"Henger",since:"Arbeid fra",back:"Tilbake"}
};
function ui(){return TEXT[document.documentElement.lang||"pl"]||TEXT.pl;}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='history')setTimeout(()=>$('#historyQuery')?.focus(),100);}
function tile(icon,title,hint,target){return `<button class="dashboard-tile" type="button" data-dashboard-view="${target}"><span class="dashboard-tile-icon">${icon}</span><div><strong>${title}</strong><span>${hint}</span></div></button>`;}
async function renderDashboard(){const t=ui();const [settings,day]=await Promise.all([get(STORES.settings,'main'),getDay(dateId())]);const profile=settings?.workProfile==='europris'?'Europris':(document.documentElement.lang==='pl'?'Uniwersalny':'Universal');const trailer=day?.trailerId||day?.trailerNumber||'Solo';$('#view-home').innerHTML=`<div class="brand-strip"><div class="brand-rumcajs"><img src="./assets/rumcajs-mark.svg" alt="Rumcajs"><span>${t.produced}</span></div><div class="brand-title"><strong>${t.title}</strong><small id="dashboardVersion"></small></div></div><div class="dashboard-status"><div><span>${t.profile}</span><strong>${profile}</strong></div><div><span>${t.truck}</span><strong>${day?.truckId||'—'}</strong></div><div><span>${t.trailer}</span><strong>${trailer}</strong></div><div><span>${t.since}</span><strong>${day?.finalStartTime||'—'}</strong></div></div><div class="dashboard-grid">${tile('🕒',t.workday,t.workdayHint,'workday')}${tile('📦',t.operations,t.operationsHint,'operations')}${tile('💰',t.payments,t.paymentsHint,'payments')}${tile('📖',t.history,t.historyHint,'history')}${tile('🚛',t.vehicles,t.vehiclesHint,'vehicles')}${tile('📍',t.places,t.placesHint,'places')}${tile('⚙️',t.settings,t.settingsHint,'settings')}</div>`;$('#dashboardVersion').textContent=$('#appVersion')?.textContent||'';$$('[data-dashboard-view]').forEach(b=>b.onclick=()=>showView(b.dataset.dashboardView));}
function bindBackButtons(){$$('.module-back').forEach(b=>b.onclick=()=>showView('home'));}
function bindSpecialViews(){document.addEventListener('click',e=>{const target=e.target.closest('[data-open-settings]');if(target)showView('settings');});}
function boot(){renderDashboard().catch(console.error);bindBackButtons();bindSpecialViews();document.querySelector('.nav-button[data-view="home"]')?.addEventListener('click',()=>setTimeout(()=>renderDashboard().catch(console.error),0));document.addEventListener('visibilitychange',()=>{if(!document.hidden&&$('#view-home')?.classList.contains('active'))renderDashboard().catch(console.error);});}
boot();
