import "./operation-controls-fix.js";
import "./places-manager.js";
import "./innovation-pack.js";
import "./workday-layout.js";
import "./workday-odometer.js";
import "./workday-odometer-finish.js";
import "./workday-action-state.js";
import "./app-information.js";
import "./journal-archive.js";
import "./timeline-operation-times.js";
import "./dynamic-view-activation-fix.js";
import "./transport-profile.js";
import "./data-health.js";
import "./cargo-items.js";
import { get, STORES } from "./db/indexeddb.js";
import { getDay } from "./modules/workdays.js";
import { dateId } from "./modules/time.js";

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const TEXT={pl:{workday:"Aktywny dzień pracy",workdayHint:"Czas, pojazd, naczepa i zdarzenia zestawu",operations:"Załadunki i rozładunki",operationsHint:"Rozpoczęcie, zakończenie i edycja operacji",payments:"Rozliczenie / stawki",paymentsHint:"Stawki, nadgodziny i godziny nocne",history:"Archiwum",historyHint:"Wyszukiwanie po całej historii",vehicles:"Pojazdy i naczepy",vehiclesHint:"Historia według numeru rejestracyjnego",stats:"Statystyki",statsHint:"Kilometry, operacje i najczęstsze miejsca",life:"Oś życia kierowcy",lifeHint:"Dni pracy z rozwijaną pełną historią",transport:"Konfiguracja transportu",transportHint:"Typ pojazdu, zabudowy i jednostka ładunku",places:"Miejsca",placesHint:"Zapisane adresy i lokalizacje GPS",settings:"Ustawienia",settingsHint:"Profil, przewoźnik i kopia danych",produced:"Wyprodukował Rumcajs",title:"Osobisty dziennik kierowcy",profile:"Profil",truck:"Samochód",trailer:"Naczepa",since:"Praca od"},en:{workday:"Active workday",workdayHint:"Time, vehicle, trailer and combination events",operations:"Loading and unloading",operationsHint:"Start, finish and edit operations",payments:"Payments / rates",paymentsHint:"Rates, overtime and night work",history:"Archive",historyHint:"Search the full journal",vehicles:"Vehicles and trailers",vehiclesHint:"History by registration number",stats:"Statistics",statsHint:"Distance, operations and top places",life:"Driver timeline",lifeHint:"Workdays with expandable full history",transport:"Transport configuration",transportHint:"Vehicle, body and cargo unit",places:"Places",placesHint:"Saved addresses and GPS locations",settings:"Settings",settingsHint:"Profile, carrier and backup",produced:"Produced by Rumcajs",title:"Driver's personal journal",profile:"Profile",truck:"Vehicle",trailer:"Trailer",since:"Working since"}};
const ui=()=>TEXT[document.documentElement.lang||"pl"]||TEXT.en;
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'});document.dispatchEvent(new CustomEvent('dashboard-view-opened',{detail:name}));}
function openModule(name){if(name==='settings'){document.querySelector('.nav-button[data-view="settings"]')?.click();setTimeout(()=>document.dispatchEvent(new CustomEvent('dashboard-view-opened',{detail:'settings'})),0);return;}if(name==='payments'){$('#openPaymentsButton')?.click();setTimeout(()=>document.dispatchEvent(new CustomEvent('dashboard-view-opened',{detail:'payments'})),0);return;}showView(name);}
const tile=(icon,title,hint,target)=>`<button class="dashboard-tile dashboard-${target}" type="button" data-dashboard-view="${target}"><span class="dashboard-tile-icon">${icon}</span><div><strong>${title}</strong><span>${hint}</span></div></button>`;
async function renderDashboard(){const home=$('#view-home');if(!home)return;const t=ui();let settings=null,day=null;try{[settings,day]=await Promise.all([get(STORES.settings,'main'),getDay(dateId())]);}catch(error){console.error(error);}const profile=settings?.workProfile==='europris'?'Europris':(document.documentElement.lang==='pl'?'Uniwersalny':'Universal'),trailer=day?.trailerId||day?.trailerNumber||'Solo';home.innerHTML=`<div class="brand-strip"><div class="brand-rumcajs"><img src="./assets/rumcajs-logo.svg" alt="Rumcajs"><span>${t.produced}</span></div><div class="brand-title"><strong>${t.title}</strong><small id="dashboardVersion"></small></div></div><div class="dashboard-status"><div><span>${t.profile}</span><strong>${profile}</strong></div><div><span>${t.truck}</span><strong>${day?.truckId||'—'}</strong></div><div><span>${t.trailer}</span><strong>${trailer}</strong></div><div><span>${t.since}</span><strong>${day?.finalStartTime||'—'}</strong></div></div><div class="dashboard-grid">${tile('🕒',t.workday,t.workdayHint,'workday')}${tile('📦',t.operations,t.operationsHint,'operations')}${tile('📖',t.history,t.historyHint,'history')}${tile('🧭',t.life,t.lifeHint,'life')}${tile('📊',t.stats,t.statsHint,'stats')}${tile('🚛',t.vehicles,t.vehiclesHint,'vehicles')}${settings?.workProfile==='universal'?tile('⚙️',t.transport,t.transportHint,'transport'):''}${tile('💰',t.payments,t.paymentsHint,'payments')}${tile('📍',t.places,t.placesHint,'places')}${tile('⚙️',t.settings,t.settingsHint,'settings')}</div>`;$('#dashboardVersion').textContent=$('#appVersion')?.textContent||'';document.dispatchEvent(new CustomEvent('dashboard-view-opened',{detail:'home'}));}
function boot(){renderDashboard().catch(console.error);document.addEventListener('click',e=>{const m=e.target.closest('[data-dashboard-view]');if(m){e.preventDefault();openModule(m.dataset.dashboardView);return;}if(e.target.closest('[data-open-settings]'))openModule('settings');if(e.target.closest('.module-back'))showView('home');});document.querySelector('.nav-button[data-view="home"]')?.addEventListener('click',()=>setTimeout(()=>renderDashboard().catch(console.error),0));document.addEventListener('visibilitychange',()=>{if(!document.hidden&&$('#view-home')?.classList.contains('active'))renderDashboard().catch(console.error);});document.addEventListener('profile-changed',()=>renderDashboard().catch(console.error));}
boot();
