import { getAll, STORES } from "./db/indexeddb.js";
import { saveDay } from "./modules/workdays.js";

const $=s=>document.querySelector(s);
const KEY="rumcajs-last-backup-time";
const TEXT={
 pl:{title:"Kontrola danych",days:"Dni zapisane",ops:"Operacje",places:"Miejsca",backup:"Ostatnia kopia",never:"Brak wykonanej kopii",today:"dzisiaj",old:"Kopia jest starsza niż 14 dni",ok:"Dane wyglądają poprawnie",open:"Otwarte dni",missingEnd:"dni bez zakończenia",make:"Wykonaj kopię teraz",show:"Sprawdź niezakończone dni",dialog:"Niezakończone dni pracy",activeToday:"Dzisiejszy aktywny dzień",older:"Starszy niezakończony dzień",started:"Rozpoczęcie",finish:"Wpisz zakończenie",save:"Zapisz zakończenie",cancel:"Anuluj",saved:"Zakończenie dnia zapisane",invalid:"Podaj godzinę zakończenia",none:"Nie ma niezakończonych dni"},
 en:{title:"Data health",days:"Saved days",ops:"Operations",places:"Places",backup:"Last backup",never:"No backup created",today:"today",old:"Backup is older than 14 days",ok:"Data looks correct",open:"Open days",missingEnd:"days without finish",make:"Create backup now",show:"Check unfinished days",dialog:"Unfinished workdays",activeToday:"Today's active workday",older:"Older unfinished workday",started:"Started",finish:"Enter finish time",save:"Save finish",cancel:"Cancel",saved:"Workday finish saved",invalid:"Enter finish time",none:"There are no unfinished days"}
};
const t=()=>TEXT[document.documentElement.lang]||TEXT.pl;
function style(){if($("#dataHealthStyle"))return;const s=document.createElement("style");s.id="dataHealthStyle";s.textContent=`.data-health-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.data-health-grid div{border:1px solid var(--line);border-radius:12px;padding:9px}.data-health-grid span{display:block;color:var(--muted);font-size:.75rem}.data-health-grid strong{font-size:1.05rem}.data-health-alert{margin-top:10px;padding:9px 11px;border-radius:11px;background:#e7f5eb;color:#176936;font-weight:700}.data-health-alert.warn{background:#fff0c7;color:#7a4c00}.data-health-alert.clickable{cursor:pointer;border:0;width:100%;text-align:left}.unfinished-dialog{position:fixed;inset:0;z-index:3000;background:rgba(0,0,0,.55);display:flex;align-items:flex-end;justify-content:center;padding:12px}.unfinished-panel{width:min(100%,560px);max-height:88vh;overflow:auto;background:var(--card);border-radius:18px 18px 12px 12px;padding:16px}.unfinished-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.unfinished-list{display:grid;gap:10px;margin-top:12px}.unfinished-item{border:1px solid var(--line);border-radius:14px;padding:12px}.unfinished-item strong,.unfinished-item span{display:block}.unfinished-item span{color:var(--muted);font-size:.85rem;margin-top:3px}.unfinished-item form{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:end;margin-top:10px}.unfinished-item input{min-height:44px}.unfinished-close{width:44px;height:44px;padding:0;font-size:1.4rem}@media(min-width:560px){.data-health-grid{grid-template-columns:repeat(4,1fr)}.unfinished-dialog{align-items:center}.unfinished-panel{border-radius:18px}}`;document.head.appendChild(s);}
function ageText(ts){if(!ts)return t().never;const d=new Date(Number(ts));if(new Date().toDateString()===d.toDateString())return t().today;return d.toLocaleDateString();}
function dateLabel(id){const d=new Date(`${id}T12:00:00`);return Number.isNaN(d.getTime())?id:new Intl.DateTimeFormat(document.documentElement.lang==="no"?"nb-NO":document.documentElement.lang||"pl-PL",{weekday:"long",year:"numeric",month:"long",day:"numeric"}).format(d);}
function todayId(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function toast(text){const box=$("#toast");if(!box)return;box.textContent=text;box.classList.remove("hidden");clearTimeout(toast.timer);toast.timer=setTimeout(()=>box.classList.add("hidden"),2400);}
function closeDialog(){$("#unfinishedDaysDialog")?.remove();}
async function openUnfinishedDays(){const days=(await getAll(STORES.workdays)).filter(d=>d.finalStartTime&&!d.finalEndTime).sort((a,b)=>String(b.id).localeCompare(String(a.id)));closeDialog();const dialog=document.createElement("div");dialog.id="unfinishedDaysDialog";dialog.className="unfinished-dialog";dialog.innerHTML=`<section class="unfinished-panel" role="dialog" aria-modal="true"><div class="unfinished-head"><div><small>${t().open.toUpperCase()}</small><h2>${t().dialog}</h2></div><button class="unfinished-close" type="button" aria-label="${t().cancel}">×</button></div><div class="unfinished-list">${days.length?days.map(day=>`<article class="unfinished-item"><strong>${dateLabel(day.id)}</strong><span>${day.id===todayId()?t().activeToday:t().older}</span><span>${t().started}: ${day.finalStartTime}</span><form data-day-id="${day.id}"><label>${t().finish}<input name="endTime" type="time" step="300" required></label><button class="primary" type="submit">${t().save}</button></form></article>`).join(""):`<p class="muted">${t().none}</p>`}</div></section>`;document.body.appendChild(dialog);dialog.querySelector(".unfinished-close").onclick=closeDialog;dialog.addEventListener("click",e=>{if(e.target===dialog)closeDialog();});dialog.querySelectorAll("form[data-day-id]").forEach(form=>form.addEventListener("submit",async e=>{e.preventDefault();const endTime=new FormData(form).get("endTime");if(!endTime)return toast(t().invalid);const id=form.dataset.dayId;await saveDay({id,date:id,finalEndTime:String(endTime),detectedEndTime:String(endTime),manuallyAdjusted:true});toast(t().saved);await render();await openUnfinishedDays();document.dispatchEvent(new CustomEvent("workday-updated",{detail:{id}}));}));}
async function render(){style();const settings=$("#view-settings");if(!settings)return;let card=$("#dataHealthCard");if(!card){card=document.createElement("article");card.id="dataHealthCard";card.className="card";const backup=[...settings.querySelectorAll("article.card")].find(x=>x.textContent.includes("KOPIA")||x.textContent.includes("Dane lokalne"));settings.insertBefore(card,backup||null);}const [days,ops,places]=await Promise.all([getAll(STORES.workdays),getAll(STORES.operations),getAll(STORES.places)]);const open=days.filter(d=>d.finalStartTime&&!d.finalEndTime).length,last=localStorage.getItem(KEY),old=!last||Date.now()-Number(last)>14*86400000;card.innerHTML=`<small>${t().title.toUpperCase()}</small><div class="data-health-grid"><div><span>${t().days}</span><strong>${days.length}</strong></div><div><span>${t().ops}</span><strong>${ops.length}</strong></div><div><span>${t().places}</span><strong>${places.length}</strong></div><div><span>${t().backup}</span><strong>${ageText(last)}</strong></div></div>${open?`<button id="dataHealthOpenDays" class="data-health-alert warn clickable" type="button">${t().open}: ${open} ${t().missingEnd}. ${t().show}</button>`:`<div class="data-health-alert ${old?"warn":""}">${old?t().old:t().ok}</div>`}${open&&old?`<div class="data-health-alert warn">${t().old}</div>`:""}<button id="dataHealthBackup" class="wide" type="button">${t().make}</button>`;$("#dataHealthOpenDays")?.addEventListener("click",()=>openUnfinishedDays().catch(console.error));$("#dataHealthBackup").onclick=()=>$("#exportButton")?.click();}
function boot(){document.addEventListener("dashboard-view-opened",e=>{if(e.detail==="settings")setTimeout(()=>render().catch(console.error),80);});$("#exportButton")?.addEventListener("click",()=>{localStorage.setItem(KEY,String(Date.now()));setTimeout(()=>render().catch(console.error),500);});}
boot();