import { getAll, STORES } from "./db/indexeddb.js";

const $=s=>document.querySelector(s);
const KEY="rumcajs-last-backup-time";
const TEXT={
 pl:{title:"Kontrola danych",days:"Dni zapisane",ops:"Operacje",places:"Miejsca",backup:"Ostatnia kopia",never:"Brak wykonanej kopii",today:"dzisiaj",old:"Kopia jest starsza niż 14 dni",ok:"Dane wyglądają poprawnie",open:"Otwarte dni",missingEnd:"dni bez zakończenia",make:"Wykonaj kopię teraz"},
 en:{title:"Data health",days:"Saved days",ops:"Operations",places:"Places",backup:"Last backup",never:"No backup created",today:"today",old:"Backup is older than 14 days",ok:"Data looks correct",open:"Open days",missingEnd:"days without finish",make:"Create backup now"}
};
const t=()=>TEXT[document.documentElement.lang]||TEXT.pl;
function style(){if($("#dataHealthStyle"))return;const s=document.createElement("style");s.id="dataHealthStyle";s.textContent=`.data-health-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.data-health-grid div{border:1px solid var(--line);border-radius:12px;padding:9px}.data-health-grid span{display:block;color:var(--muted);font-size:.75rem}.data-health-grid strong{font-size:1.05rem}.data-health-alert{margin-top:10px;padding:9px 11px;border-radius:11px;background:#e7f5eb;color:#176936;font-weight:700}.data-health-alert.warn{background:#fff0c7;color:#7a4c00}@media(min-width:560px){.data-health-grid{grid-template-columns:repeat(4,1fr)}}`;document.head.appendChild(s);}
function ageText(ts){if(!ts)return t().never;const d=new Date(Number(ts));if(new Date().toDateString()===d.toDateString())return t().today;return d.toLocaleDateString();}
async function render(){style();const settings=$("#view-settings");if(!settings)return;let card=$("#dataHealthCard");if(!card){card=document.createElement("article");card.id="dataHealthCard";card.className="card";const backup=[...settings.querySelectorAll("article.card")].find(x=>x.textContent.includes("KOPIA")||x.textContent.includes("Dane lokalne"));settings.insertBefore(card,backup||null);}const [days,ops,places]=await Promise.all([getAll(STORES.workdays),getAll(STORES.operations),getAll(STORES.places)]);const open=days.filter(d=>d.finalStartTime&&!d.finalEndTime).length,last=localStorage.getItem(KEY),old=!last||Date.now()-Number(last)>14*86400000;card.innerHTML=`<small>${t().title.toUpperCase()}</small><div class="data-health-grid"><div><span>${t().days}</span><strong>${days.length}</strong></div><div><span>${t().ops}</span><strong>${ops.length}</strong></div><div><span>${t().places}</span><strong>${places.length}</strong></div><div><span>${t().backup}</span><strong>${ageText(last)}</strong></div></div><div class="data-health-alert ${old||open?"warn":""}">${open?`${t().open}: ${open} ${t().missingEnd}. `:""}${old?t().old:t().ok}</div><button id="dataHealthBackup" class="wide" type="button">${t().make}</button>`;$("#dataHealthBackup").onclick=()=>$("#exportButton")?.click();}
function boot(){document.addEventListener("dashboard-view-opened",e=>{if(e.detail==="settings")setTimeout(()=>render().catch(console.error),80);});$("#exportButton")?.addEventListener("click",()=>{localStorage.setItem(KEY,String(Date.now()));setTimeout(()=>render().catch(console.error),500);});}
boot();