import { get, getAll, STORES } from "./db/indexeddb.js";
import { getDay, saveDay } from "./modules/workdays.js";
import { getOperationsForDay } from "./modules/operations.js";
import { getSavedPlaces, markPlaceUsed } from "./modules/places.js";
import { dateId, minutesText } from "./modules/time.js";

const $ = selector => document.querySelector(selector);
const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));

const TEXT = {
  pl:{today:"Dzisiejsze podsumowanie",operations:"Operacje",pallets:"Palety",events:"Zmiany zestawu",mileage:"Kilometry",live:"Czas pracy na żywo",note:"Szybka notatka dnia",save:"Zapisz",saved:"Zapisano",check:"Kontrola dnia",documents:"Dokumenty",fuel:"Paliwo / karta",inspection:"Kontrola pojazdu",share:"Kopiuj raport dnia",copied:"Raport skopiowany",recent:"Ulubione i ostatnie miejsca",vehicles:"Statystyka pojazdów",days:"dni",last:"Ostatnio",completeness:"Kompletność zapisu",complete:"Zapis kompletny",missing:"Brakuje",truck:"pojazdu",address:"adresu rozpoczęcia",trailer:"naczepy",timeline:"Przebieg dnia"},
  en:{today:"Today's summary",operations:"Operations",pallets:"Pallets",events:"Combination changes",mileage:"Distance",live:"Live work time",note:"Quick day note",save:"Save",saved:"Saved",check:"Daily check",documents:"Documents",fuel:"Fuel / card",inspection:"Vehicle check",share:"Copy day report",copied:"Report copied",recent:"Favourite and recent places",vehicles:"Vehicle statistics",days:"days",last:"Last used",completeness:"Record completeness",complete:"Record complete",missing:"Missing",truck:"vehicle",address:"start address",trailer:"trailer",timeline:"Day timeline"},
  de:{today:"Heutige Zusammenfassung",operations:"Vorgänge",pallets:"Paletten",events:"Gespannwechsel",mileage:"Kilometer",live:"Arbeitszeit live",note:"Schnelle Tagesnotiz",save:"Speichern",saved:"Gespeichert",check:"Tageskontrolle",documents:"Dokumente",fuel:"Kraftstoff / Karte",inspection:"Fahrzeugkontrolle",share:"Tagesbericht kopieren",copied:"Bericht kopiert",recent:"Favoriten und letzte Orte",vehicles:"Fahrzeugstatistik",days:"Tage",last:"Zuletzt",completeness:"Vollständigkeit",complete:"Eintrag vollständig",missing:"Fehlt",truck:"Fahrzeug",address:"Startadresse",trailer:"Anhänger",timeline:"Tagesverlauf"},
  no:{today:"Dagens sammendrag",operations:"Operasjoner",pallets:"Paller",events:"Bytte av vogntog",mileage:"Kilometer",live:"Arbeidstid direkte",note:"Hurtignotat",save:"Lagre",saved:"Lagret",check:"Dagskontroll",documents:"Dokumenter",fuel:"Drivstoff / kort",inspection:"Kjøretøykontroll",share:"Kopier dagsrapport",copied:"Rapport kopiert",recent:"Favoritter og siste steder",vehicles:"Kjøretøystatistikk",days:"dager",last:"Sist",completeness:"Fullstendighet",complete:"Registreringen er komplett",missing:"Mangler",truck:"kjøretøy",address:"startadresse",trailer:"henger",timeline:"Dagens forløp"}
};
const t = () => TEXT[document.documentElement.lang || "pl"] || TEXT.pl;
function toast(message){const box=$("#toast");if(!box)return;box.textContent=message;box.classList.remove("hidden");clearTimeout(toast.timer);toast.timer=setTimeout(()=>box.classList.add("hidden"),2400);}
function parseMinutes(time){if(!time)return null;const [h,m]=time.split(":").map(Number);return h*60+m;}
function liveMinutes(day){const start=parseMinutes(day?.finalStartTime);if(start==null)return 0;const end=day?.finalEndTime?parseMinutes(day.finalEndTime):(new Date().getHours()*60+new Date().getMinutes());let value=end-start;if(value<0)value+=1440;return Math.max(0,value-Number(day.breakMinutes||0));}
function mileage(day){const a=Number(day?.startOdometer),b=Number(day?.endOdometer??day?.lastOdometer);return Number.isFinite(a)&&Number.isFinite(b)&&b>=a?b-a:null;}

async function dayData(){const id=dateId();const [day,operations]=await Promise.all([getDay(id),getOperationsForDay(id)]);return{day,operations};}

async function renderDashboardExtras(){const home=$("#view-home");if(!home||!home.classList.contains("active"))return;$("#innovationDashboard")?.remove();const {day,operations}=await dayData();const pallets=operations.reduce((sum,item)=>sum+Number(item.pallets||0),0);const events=day?.trailerEvents?.length||0;const km=mileage(day);const missing=[];if(day?.finalStartTime&&!day?.truckId)missing.push(t().truck);if(day?.finalStartTime&&!day?.startAddress)missing.push(t().address);const panel=document.createElement("section");panel.id="innovationDashboard";panel.className="innovation-dashboard";panel.innerHTML=`<h3>${t().today}</h3><div class="innovation-stats"><div><span>${t().live}</span><strong id="liveWorkValue">${minutesText(liveMinutes(day))}</strong></div><div><span>${t().operations}</span><strong>${operations.length}</strong></div><div><span>${t().pallets}</span><strong>${pallets}</strong></div><div><span>${t().events}</span><strong>${events}</strong></div><div><span>${t().mileage}</span><strong>${km==null?"—":`${km} km`}</strong></div></div><div class="innovation-completeness ${missing.length?"warn":"ok"}"><strong>${t().completeness}</strong><span>${missing.length?`${t().missing}: ${missing.join(", ")}`:t().complete}</span></div>`;home.appendChild(panel);}

async function renderWorkdayTools(){const view=$("#view-workday");if(!view)return;$("#journalToolsCard")?.remove();const {day,operations}=await dayData();const card=document.createElement("article");card.id="journalToolsCard";card.className="card journal-tools-card";const checklist=day?.dailyChecklist||{};const timeline=[...(operations||[]).map(o=>({time:o.startTime,label:`${o.type==="unload"?"Rozładunek":"Załadunek"}: ${o.place}`})),...((day?.trailerEvents)||[]).map(e=>({time:e.time,label:e.type==="drop"?"Odstawienie naczepy":e.type==="attach"?"Podpięcie naczepy":e.type==="truck"?"Zmiana ciągnika":"Zmiana zestawu"}))].sort((a,b)=>String(a.time).localeCompare(String(b.time)));
  card.innerHTML=`<small>DZIENNIK</small><h2>${t().note}</h2><textarea id="quickDayNote" rows="3" placeholder="...">${esc(day?.notes||"")}</textarea><div class="button-row"><button id="saveQuickDayNote" class="primary" type="button">${t().save}</button><button id="copyDayReport" type="button">${t().share}</button></div><h3>${t().check}</h3><div class="daily-checklist"><label><input type="checkbox" data-check="documents" ${checklist.documents?"checked":""}> ${t().documents}</label><label><input type="checkbox" data-check="fuel" ${checklist.fuel?"checked":""}> ${t().fuel}</label><label><input type="checkbox" data-check="inspection" ${checklist.inspection?"checked":""}> ${t().inspection}</label></div><h3>${t().timeline}</h3><div class="mini-timeline">${timeline.length?timeline.map(item=>`<div><b>${esc(item.time||"—")}</b><span>${esc(item.label)}</span></div>`).join(""):`<p class="muted">—</p>`}</div>`;
  view.appendChild(card);
  $("#saveQuickDayNote").onclick=async()=>{const current=await getDay(dateId())||{id:dateId(),date:dateId()};await saveDay({...current,notes:$("#quickDayNote").value.trim()});toast(t().saved);};
  card.querySelectorAll("[data-check]").forEach(input=>input.onchange=async()=>{const current=await getDay(dateId())||{id:dateId(),date:dateId()};const next={...(current.dailyChecklist||{}),[input.dataset.check]:input.checked};await saveDay({...current,dailyChecklist:next});toast(t().saved);});
  $("#copyDayReport").onclick=()=>copyReport(day,operations);
}

async function copyReport(day,operations){const lines=[dateId(),`Pojazd: ${day?.truckId||"—"}`,`Naczepa: ${day?.trailerId||day?.trailerNumber||"Solo"}`,`Praca: ${day?.finalStartTime||"—"}–${day?.finalEndTime||"trwa"}`,`Start: ${day?.startAddress||"—"}`,`Koniec: ${day?.endAddress||"—"}`,`Operacje: ${operations.length}`,...operations.map(o=>`${o.startTime||"—"} ${o.type==="unload"?"Rozładunek":"Załadunek"} — ${o.place}${o.endTime?` do ${o.endTime}`:""}`),day?.notes?`Notatka: ${day.notes}`:""];const text=lines.filter(Boolean).join("\n");try{await navigator.clipboard.writeText(text);toast(t().copied);}catch{if(navigator.share)await navigator.share({title:"Dziennik kierowcy",text});}}

async function renderFavoritePlaces(){const selector=$("#operationSelector");if(!selector)return;$("#quickPlaces")?.remove();const places=(await getSavedPlaces()).slice(0,6);if(!places.length)return;const box=document.createElement("div");box.id="quickPlaces";box.className="quick-places";box.innerHTML=`<strong>${t().recent}</strong><div>${places.map(p=>`<button type="button" data-place-id="${esc(p.id)}">${p.favorite?"★ ":""}${esc(p.name)}</button>`).join("")}</div>`;selector.insertBefore(box,selector.firstChild);box.querySelectorAll("button").forEach(button=>button.onclick=async()=>{const place=places.find(p=>p.id===button.dataset.placeId);if(!place)return;$("#operationPlaceSearch").value=place.name;$("#selectedPlaceLabel").textContent=place.name;$("#selectedPlaceAddress").textContent=place.address||"";$("#selectedPlaceBox").classList.remove("hidden");await markPlaceUsed(place,"quick-select");});}

async function renderVehicleStatistics(){const view=$("#view-vehicles");if(!view)return;const all=await getAll(STORES.workdays);const map=new Map();for(const day of all){if(!day.truckId)continue;const item=map.get(day.truckId)||{days:0,last:"",km:0};item.days++;if(day.date>item.last)item.last=day.date;const value=mileage(day);if(value!=null)item.km+=value;map.set(day.truckId,item);}const rows=[...map.entries()].sort((a,b)=>b[1].days-a[1].days);const placeholder=view.querySelector(".module-placeholder");if(!placeholder)return;placeholder.innerHTML=`<h2>${t().vehicles}</h2>${rows.length?`<div class="vehicle-stat-list">${rows.map(([reg,s])=>`<div><strong>${esc(reg)}</strong><span>${s.days} ${t().days} • ${s.km?`${s.km} km • `:""}${t().last}: ${esc(s.last)}</span></div>`).join("")}</div>`:`<p class="muted">—</p>`}`;}

function ensureStyle(){if($("#innovationPackStyle"))return;const style=document.createElement("style");style.id="innovationPackStyle";style.textContent=`.innovation-dashboard{margin:14px 0 90px;padding:14px;border-radius:18px;background:linear-gradient(135deg,#eef6ff,#fff8e7);border:1px solid var(--line)}.innovation-dashboard h3{margin:0 0 10px}.innovation-stats{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.innovation-stats div{padding:10px;border-radius:12px;background:var(--card);border:1px solid var(--line)}.innovation-stats span{display:block;font-size:.78rem;color:var(--muted)}.innovation-stats strong{font-size:1.05rem}.innovation-completeness{margin-top:10px;padding:10px;border-radius:12px;display:flex;flex-direction:column}.innovation-completeness.ok{background:#e9f8ef;color:#176337}.innovation-completeness.warn{background:#fff1df;color:#7a4300}.journal-tools-card textarea{width:100%;box-sizing:border-box}.daily-checklist{display:grid;gap:8px;margin:8px 0 16px}.daily-checklist label{display:flex;gap:10px;align-items:center;padding:10px;border:1px solid var(--line);border-radius:10px}.daily-checklist input{width:auto}.mini-timeline{display:grid;gap:6px}.mini-timeline div{display:grid;grid-template-columns:58px 1fr;gap:8px;padding:8px;border-left:3px solid #377dd1;background:rgba(55,125,209,.07)}.quick-places{margin-bottom:14px;padding:10px;border-radius:12px;background:#f4f8ff;border:1px solid #bfd5f3}.quick-places>div{display:flex;gap:7px;overflow-x:auto;padding-top:8px}.quick-places button{white-space:nowrap;padding:8px 10px}.vehicle-stat-list{display:grid;gap:8px}.vehicle-stat-list div{display:flex;justify-content:space-between;gap:12px;padding:12px;border:1px solid var(--line);border-radius:12px}.vehicle-stat-list span{color:var(--muted);text-align:right}@media(min-width:650px){.innovation-stats{grid-template-columns:repeat(5,1fr)}}`;document.head.appendChild(style);}

async function refreshView(name){if(name==="home")await renderDashboardExtras();if(name==="workday")await renderWorkdayTools();if(name==="operations")await renderFavoritePlaces();if(name==="vehicles")await renderVehicleStatistics();}
function boot(){ensureStyle();setTimeout(()=>refreshView("home").catch(console.error),500);document.addEventListener("dashboard-view-opened",event=>setTimeout(()=>refreshView(event.detail).catch(console.error),80));document.addEventListener("vehicle-data-changed",()=>setTimeout(()=>renderWorkdayTools().catch(console.error),120));setInterval(()=>{const value=$("#liveWorkValue");if(value)getDay(dateId()).then(day=>value.textContent=minutesText(liveMinutes(day))).catch(()=>{});},60000);}
boot();