import { getAll, STORES } from "./db/indexeddb.js";

const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const norm=v=>String(v??"").toLocaleLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
const lang=()=>document.documentElement.lang||"pl";
const TXT={
 pl:{back:"← Start",archive:"Archiwum i wyszukiwarka",search:"Szukaj po aucie, naczepie, miejscu, adresie, notatce lub dacie",all:"Wszystko",days:"Dni",loads:"Załadunki",unloads:"Rozładunki",vehicles:"Pojazdy i naczepy",no:"Brak wyników",stats:"Statystyki",life:"Oś życia kierowcy",workDays:"Dni pracy",km:"Kilometry",loadCount:"Załadunki",unloadCount:"Rozładunki",topPlaces:"Najczęstsze miejsca",topTrucks:"Najczęstsze samochody",topTrailers:"Najczęstsze naczepy",period:"Okres",month:"Miesiąc",year:"Rok",allTime:"Cały okres",vehicleHistory:"Historia pojazdu lub naczepy",reg:"Wpisz numer rejestracyjny",last:"Ostatnie użycie",events:"zdarzeń",start:"Rozpoczęcie pracy",end:"Zakończenie pracy",change:"Zmiana zestawu",note:"Notatka",distance:"Przebieg dnia"},
 en:{back:"← Home",archive:"Archive and search",search:"Search vehicle, trailer, place, address, note or date",all:"All",days:"Days",loads:"Loads",unloads:"Unloads",vehicles:"Vehicles and trailers",no:"No results",stats:"Statistics",life:"Driver timeline",workDays:"Work days",km:"Kilometres",loadCount:"Loads",unloadCount:"Unloads",topPlaces:"Top places",topTrucks:"Top vehicles",topTrailers:"Top trailers",period:"Period",month:"Month",year:"Year",allTime:"All time",vehicleHistory:"Vehicle or trailer history",reg:"Enter registration",last:"Last used",events:"events",start:"Work started",end:"Work finished",change:"Combination change",note:"Note",distance:"Day distance"}
};
const t=()=>TXT[lang()]||TXT.en;
let cache={days:[],ops:[]};
function addStyle(){if($("#journalArchiveStyle"))return;const s=document.createElement("style");s.id="journalArchiveStyle";s.textContent=`.journal-page{display:grid;gap:12px}.journal-toolbar{display:grid;grid-template-columns:1fr auto;gap:8px}.journal-toolbar input,.journal-toolbar select{margin:0}.journal-tabs{display:flex;gap:6px;overflow:auto}.journal-tabs button{min-height:38px;padding:7px 11px;white-space:nowrap}.journal-result{border:1px solid var(--line);border-radius:13px;padding:10px;background:var(--card)}.journal-result h3{margin:0 0 5px;font-size:.98rem}.journal-result p{margin:3px 0;color:var(--muted);font-size:.86rem}.journal-badge{display:inline-block;padding:3px 7px;border-radius:999px;background:var(--bg);font-size:.72rem;margin-right:5px}.journal-stats{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.journal-stat{border:1px solid var(--line);border-radius:13px;padding:10px}.journal-stat span{display:block;color:var(--muted);font-size:.78rem}.journal-stat strong{font-size:1.25rem}.journal-ranking{display:grid;gap:6px}.journal-ranking div{display:flex;justify-content:space-between;border-bottom:1px solid var(--line);padding:6px 0}.life-item{display:grid;grid-template-columns:70px 1fr;gap:8px;padding:9px 0;border-bottom:1px solid var(--line)}.life-item time{font-weight:800}.life-item small{display:block;color:var(--muted)}@media(min-width:560px){.journal-stats{grid-template-columns:repeat(4,1fr)}}`;document.head.appendChild(s);}
function ensureView(id,title){let v=$("#view-"+id);if(!v){v=document.createElement("section");v.id="view-"+id;v.className="view";document.querySelector("main")?.appendChild(v);}v.innerHTML=`<div class="module-head"><button class="module-back" type="button">${t().back}</button><div><h2>${title}</h2></div></div><div id="${id}Body" class="journal-page"></div>`;return v;}
async function load(){cache.days=await getAll(STORES.workdays);cache.ops=await getAll(STORES.operations);cache.days.sort((a,b)=>String(b.id).localeCompare(String(a.id)));cache.ops.sort((a,b)=>String(b.workdayId||b.date||"").localeCompare(String(a.workdayId||a.date||"")));}
function dayText(d){return [d.id,d.truckId,d.trailerId,d.trailerNumber,d.startAddress,d.endAddress,d.notes,d.dayNote,d.driverName,...(d.vehicleChanges||[]).flatMap(x=>Object.values(x))].join(" ");}
function opText(o){return [o.workdayId,o.type,o.place,o.storeName,o.storeAddress,o.notes,o.pallets,o.emptyPallets].join(" ");}
function renderArchive(){ensureView("history",t().archive);const b=$("#historyBody");b.innerHTML=`<div class="journal-toolbar"><input id="archiveQuery" placeholder="${t().search}"><select id="archivePeriod"><option value="all">${t().allTime}</option><option value="month">${t().month}</option><option value="year">${t().year}</option></select></div><div class="journal-tabs"><button data-kind="all">${t().all}</button><button data-kind="days">${t().days}</button><button data-kind="load">${t().loads}</button><button data-kind="unload">${t().unloads}</button></div><div id="archiveResults"></div>`;let kind="all";const draw=()=>{const q=norm($("#archiveQuery").value),period=$("#archivePeriod").value,now=new Date();const allowDate=id=>{if(period==="all")return true;const d=new Date(id);return period==="month"?d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth():d.getFullYear()===now.getFullYear();};let rows=[];if(kind==="all"||kind==="days")for(const d of cache.days)if(allowDate(d.id)&&(!q||norm(dayText(d)).includes(q)))rows.push({date:d.id,title:`${d.truckId||"—"} / ${d.trailerId||d.trailerNumber||"Solo"}`,meta:`${d.finalStartTime||"—"} – ${d.finalEndTime||"—"}${d.startOdometer!=null&&d.endOdometer!=null?` • ${d.endOdometer-d.startOdometer} km`:""}`,body:d.notes||d.dayNote||d.startAddress||""});if(kind!=="days")for(const o of cache.ops)if((kind==="all"||kind===o.type)&&allowDate(o.workdayId||o.date)&&(!q||norm(opText(o)).includes(q)))rows.push({date:o.workdayId||o.date,title:`${o.type==="load"?t().loadCount:t().unloadCount}: ${o.place||o.storeName||"—"}`,meta:`${o.startTime||"—"} – ${o.endTime||"…"}`,body:o.storeAddress||o.notes||""});rows.sort((a,b)=>String(b.date).localeCompare(String(a.date)));$("#archiveResults").innerHTML=rows.length?rows.slice(0,300).map(r=>`<article class="journal-result"><span class="journal-badge">${esc(r.date)}</span><h3>${esc(r.title)}</h3><p>${esc(r.meta)}</p>${r.body?`<p>${esc(r.body)}</p>`:""}</article>`).join(""):`<p class="muted">${t().no}</p>`;};$("#archiveQuery").oninput=draw;$("#archivePeriod").onchange=draw;b.querySelectorAll("[data-kind]").forEach(x=>x.onclick=()=>{kind=x.dataset.kind;draw();});draw();}
function countBy(items,keyfn){const m=new Map();for(const x of items){const k=keyfn(x);if(k)m.set(k,(m.get(k)||0)+1);}return [...m].sort((a,b)=>b[1]-a[1]);}
function ranking(title,data){return `<section class="card"><h3>${title}</h3><div class="journal-ranking">${data.slice(0,10).map(([k,v])=>`<div><span>${esc(k)}</span><strong>${v}</strong></div>`).join("")||`<p class="muted">${t().no}</p>`}</div></section>`;}
function renderStats(){ensureView("stats",t().stats);const days=cache.days.filter(d=>d.finalStartTime),km=days.reduce((s,d)=>s+(d.startOdometer!=null&&d.endOdometer>=d.startOdometer?d.endOdometer-d.startOdometer:0),0),loads=cache.ops.filter(o=>o.type==="load").length,unloads=cache.ops.filter(o=>o.type==="unload").length;$("#statsBody").innerHTML=`<div class="journal-stats"><div class="journal-stat"><span>${t().workDays}</span><strong>${days.length}</strong></div><div class="journal-stat"><span>${t().km}</span><strong>${km}</strong></div><div class="journal-stat"><span>${t().loadCount}</span><strong>${loads}</strong></div><div class="journal-stat"><span>${t().unloadCount}</span><strong>${unloads}</strong></div></div>${ranking(t().topPlaces,countBy(cache.ops,o=>o.place||o.storeName))}${ranking(t().topTrucks,countBy(days,d=>d.truckId))}${ranking(t().topTrailers,countBy(days,d=>d.trailerId||d.trailerNumber))}`;}
function allEvents(){const e=[];for(const d of cache.days){if(d.finalStartTime)e.push({date:d.id,time:d.finalStartTime,title:t().start,detail:d.startAddress||d.truckId||""});for(const c of d.vehicleChanges||[])e.push({date:d.id,time:c.time,title:t().change,detail:`${c.fromTruck||"—"}/${c.fromTrailer||"—"} → ${c.toTruck||"—"}/${c.toTrailer||"—"}`});if(d.notes||d.dayNote)e.push({date:d.id,time:"",title:t().note,detail:d.notes||d.dayNote});if(d.finalEndTime)e.push({date:d.id,time:d.finalEndTime,title:t().end,detail:d.endAddress||""});}for(const o of cache.ops)e.push({date:o.workdayId||o.date,time:o.startTime||"",title:o.type==="load"?t().loadCount:t().unloadCount,detail:o.place||o.storeName||""});return e.sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));}
function renderLife(){ensureView("life",t().life);const b=$("#lifeBody"),events=allEvents();b.innerHTML=`<input id="lifeQuery" placeholder="${t().search}"><div id="lifeRows"></div>`;const draw=()=>{const q=norm($("#lifeQuery").value),rows=events.filter(e=>!q||norm(Object.values(e).join(" ")).includes(q));$("#lifeRows").innerHTML=rows.slice(0,500).map(e=>`<div class="life-item"><time>${esc(e.date)}<small>${esc(e.time)}</small></time><div><strong>${esc(e.title)}</strong><small>${esc(e.detail)}</small></div></div>`).join("")||`<p class="muted">${t().no}</p>`;};$("#lifeQuery").oninput=draw;draw();}
function renderVehicles(){ensureView("vehicles",t().vehicleHistory);const b=$("#vehiclesBody");b.innerHTML=`<input id="vehicleHistoryQuery" placeholder="${t().reg}"><div id="vehicleHistoryRows"></div>`;const draw=()=>{const q=norm($("#vehicleHistoryQuery").value);if(!q){$("#vehicleHistoryRows").innerHTML=ranking(t().topTrucks,countBy(cache.days,d=>d.truckId))+ranking(t().topTrailers,countBy(cache.days,d=>d.trailerId||d.trailerNumber));return;}const rows=[];for(const d of cache.days)if(norm(`${d.truckId} ${d.trailerId} ${d.trailerNumber} ${(d.vehicleChanges||[]).map(x=>Object.values(x).join(" ")).join(" ")}`).includes(q))rows.push({date:d.id,title:`${d.truckId||"—"} / ${d.trailerId||d.trailerNumber||"Solo"}`,meta:`${d.finalStartTime||"—"} – ${d.finalEndTime||"—"}`,body:d.startAddress||d.endAddress||d.notes||""});$("#vehicleHistoryRows").innerHTML=rows.map(r=>`<article class="journal-result"><span class="journal-badge">${r.date}</span><h3>${esc(r.title)}</h3><p>${esc(r.meta)}</p><p>${esc(r.body)}</p></article>`).join("")||`<p class="muted">${t().no}</p>`;};$("#vehicleHistoryQuery").oninput=draw;draw();}
async function render(name){await load();if(name==="history")renderArchive();if(name==="stats")renderStats();if(name==="life")renderLife();if(name==="vehicles")renderVehicles();}
function boot(){addStyle();document.addEventListener("dashboard-view-opened",e=>{if(["history","stats","life","vehicles"].includes(e.detail))render(e.detail).catch(console.error);});}
boot();
