import { getSavedPlaces, updatePlace, deletePlace } from "./modules/places.js";

const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const TEXT={
  pl:{title:"Zapisane miejsca",hint:"Ulubione, ostatnio używane i rozpoznawane przez GPS.",search:"Szukaj miejsca",empty:"Brak zapisanych miejsc.",visits:"Wizyty",last:"Ostatnio",edit:"Edytuj",save:"Zapisz",cancel:"Anuluj",remove:"Usuń",favorite:"Ulubione",lock:"Blokada",name:"Nazwa miejsca",address:"Adres",confirm:"Usunąć to miejsce?",locked:"Miejsce zablokowane przed usunięciem",saved:"Miejsce zapisane"},
  en:{title:"Saved places",hint:"Favourites, recent places and GPS recognition.",search:"Search places",empty:"No saved places.",visits:"Visits",last:"Last used",edit:"Edit",save:"Save",cancel:"Cancel",remove:"Delete",favorite:"Favourite",lock:"Lock",name:"Place name",address:"Address",confirm:"Delete this place?",locked:"Place protected from deletion",saved:"Place saved"},
  de:{title:"Gespeicherte Orte",hint:"Favoriten, zuletzt verwendet und GPS-Erkennung.",search:"Orte suchen",empty:"Keine gespeicherten Orte.",visits:"Besuche",last:"Zuletzt",edit:"Bearbeiten",save:"Speichern",cancel:"Abbrechen",remove:"Löschen",favorite:"Favorit",lock:"Sperre",name:"Ortsname",address:"Adresse",confirm:"Diesen Ort löschen?",locked:"Ort ist vor Löschen geschützt",saved:"Ort gespeichert"},
  no:{title:"Lagrede steder",hint:"Favoritter, nylig brukt og GPS-gjenkjenning.",search:"Søk etter sted",empty:"Ingen lagrede steder.",visits:"Besøk",last:"Sist brukt",edit:"Rediger",save:"Lagre",cancel:"Avbryt",remove:"Slett",favorite:"Favoritt",lock:"Lås",name:"Stedsnavn",address:"Adresse",confirm:"Slette dette stedet?",locked:"Stedet er beskyttet mot sletting",saved:"Sted lagret"}
};
function t(){return TEXT[document.documentElement.lang||"pl"]||TEXT.pl;}
function toast(m){const b=$("#toast");if(!b)return;b.textContent=m;b.classList.remove("hidden");clearTimeout(toast.timer);toast.timer=setTimeout(()=>b.classList.add("hidden"),2500);}
function dateText(value){if(!value)return "—";return new Intl.DateTimeFormat(document.documentElement.lang||"pl",{dateStyle:"medium"}).format(new Date(value));}
function ensureStyle(){if($("#placesManagerStyle"))return;const s=document.createElement("style");s.id="placesManagerStyle";s.textContent=`.places-toolbar{display:grid;grid-template-columns:1fr;gap:10px;margin-bottom:12px}.places-list{display:grid;gap:10px}.place-card{padding:13px;border:1px solid var(--line);border-radius:14px;background:var(--card)}.place-card.favorite{border-color:#d59b27;box-shadow:0 0 0 1px #d59b27 inset}.place-head{display:flex;justify-content:space-between;gap:10px}.place-head strong{overflow-wrap:anywhere}.place-icons{white-space:nowrap}.place-address,.place-meta{display:block;color:var(--muted);margin-top:5px;font-size:.84rem}.place-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:11px}.place-actions button{padding:9px}.place-edit{margin-top:12px;padding-top:12px;border-top:1px solid var(--line)}.place-edit.hidden{display:none}.place-edit label{display:block;margin-top:8px}`;document.head.appendChild(s);}
async function render(){const view=$("#view-places");if(!view)return;ensureStyle();const q=String($("#placesSearch")?.value||"").trim().toLowerCase();const all=await getSavedPlaces();const items=all.filter(p=>!q||`${p.name} ${p.address||""}`.toLowerCase().includes(q));view.innerHTML=`<div class="module-head"><button class="module-back" type="button">‹</button><div><small>MIEJSCA</small><h2>${t().title}</h2></div></div><article class="card"><p class="muted">${t().hint}</p><div class="places-toolbar"><input id="placesSearch" type="search" placeholder="${t().search}" value="${esc(q)}"></div><div id="placesList" class="places-list">${items.length?items.map(card).join(""):`<p class="muted">${t().empty}</p>`}</div></article>`;$("#placesSearch")?.addEventListener("input",()=>setTimeout(render,0));bind();}
function card(p){const count=Number(p.visitCount||0);return `<div class="place-card ${p.favorite?"favorite":""}" data-place-id="${esc(p.id)}"><div class="place-head"><strong>${p.favorite?"⭐ ":""}${esc(p.name)}</strong><span class="place-icons">${p.locked?"🔒":""}</span></div><span class="place-address">${esc(p.address||"—")}</span><span class="place-meta">${t().visits}: ${count} • ${t().last}: ${dateText(p.lastUsedAt)}</span><div class="place-actions"><button data-place-action="favorite" type="button">${p.favorite?"★":"☆"}</button><button data-place-action="lock" type="button">${p.locked?"🔒":"🔓"}</button><button data-place-action="edit" type="button">${t().edit}</button></div><div class="place-edit hidden"><label>${t().name}<input data-edit-name value="${esc(p.name)}"></label><label>${t().address}<input data-edit-address value="${esc(p.address||"")}"></label><div class="button-row"><button class="primary" data-place-action="save" type="button">${t().save}</button><button data-place-action="delete" type="button">${t().remove}</button></div></div></div>`;}
function bind(){document.querySelectorAll("[data-place-action]").forEach(b=>b.addEventListener("click",handle));}
async function handle(e){const button=e.currentTarget,card=button.closest("[data-place-id]"),id=card?.dataset.placeId,action=button.dataset.placeAction;if(!id)return;const places=await getSavedPlaces(),place=places.find(p=>p.id===id);if(!place)return;if(action==="edit"){card.querySelector(".place-edit")?.classList.toggle("hidden");return;}if(action==="favorite")await updatePlace(id,{favorite:!place.favorite});if(action==="lock")await updatePlace(id,{locked:!place.locked});if(action==="save"){const name=card.querySelector("[data-edit-name]").value.trim();const address=card.querySelector("[data-edit-address]").value.trim();if(!name)return card.querySelector("[data-edit-name]").focus();await updatePlace(id,{name,address});toast(t().saved);}if(action==="delete"){if(place.locked)return toast(t().locked);if(!confirm(t().confirm))return;await deletePlace(id);}await render();}
document.addEventListener("dashboard-view-opened",e=>{if(e.detail==="places")render().catch(console.error);});document.addEventListener("click",e=>{if(e.target.closest('[data-dashboard-view="places"]'))setTimeout(()=>render().catch(console.error),0);});