import { getAll, STORES } from "./db/indexeddb.js";

const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const lang=()=>document.documentElement.lang||"pl";
const TXT={
pl:{title:"Raporty / Eksport",back:"← Start",scope:"Zakres raportu",day:"Jeden dzień",month:"Miesiąc",type:"Typ raportu",summary:"Podsumowanie dni",details:"Szczegóły operacji",fields:"Wybierz kolumny",required:"obowiązkowa",preview:"Podgląd raportu",excel:"Eksport Excel",print:"Drukuj / PDF",saveLayout:"Zapamiętaj mój układ",saved:"Układ zapisany",noData:"Brak danych dla wybranego okresu",date:"Data",weekday:"Dzień tygodnia",driver:"Kierowca",start:"Rozpoczęcie pracy",end:"Zakończenie pracy",workTime:"Czas pracy",breakTime:"Przerwa",net:"Czas netto",truck:"Samochód",trailer:"Naczepa",odoStart:"Licznik początkowy",odoEnd:"Licznik końcowy",km:"Kilometry",startPlace:"Miejsce rozpoczęcia",endPlace:"Miejsce zakończenia",loads:"Załadunki",unloads:"Rozładunki",pallets:"Ilość palet",emptyPallets:"Puste palety",places:"Miejsca operacji",opTimes:"Godziny operacji",notes:"Notatki",operation:"Typ operacji",operationPlace:"Miejsce operacji",operationStart:"Start operacji",operationEnd:"Koniec operacji",daysCount:"Dni",totalNet:"Łączny czas netto",totalKm:"Łączne km",totalPallets:"Łącznie palet"},
en:{title:"Reports / Export",back:"← Home",scope:"Report range",day:"One day",month:"Month",type:"Report type",summary:"Day summary",details:"Operation details",fields:"Choose columns",required:"required",preview:"Report preview",excel:"Export Excel",print:"Print / PDF",saveLayout:"Remember my layout",saved:"Layout saved",noData:"No data for selected period",date:"Date",weekday:"Weekday",driver:"Driver",start:"Work start",end:"Work end",workTime:"Work time",breakTime:"Break",net:"Net time",truck:"Vehicle",trailer:"Trailer",odoStart:"Start odometer",odoEnd:"End odometer",km:"Kilometres",startPlace:"Start location",endPlace:"End location",loads:"Loads",unloads:"Unloads",pallets:"Pallets",emptyPallets:"Empty pallets",places:"Operation places",opTimes:"Operation times",notes:"Notes",operation:"Operation type",operationPlace:"Operation place",operationStart:"Operation start",operationEnd:"Operation end",daysCount:"Days",totalNet:"Total net time",totalKm:"Total km",totalPallets:"Total pallets"},
de:{title:"Berichte / Export",back:"← Start",scope:"Berichtszeitraum",day:"Ein Tag",month:"Monat",type:"Berichtstyp",summary:"Tagesübersicht",details:"Vorgangsdetails",fields:"Spalten auswählen",required:"Pflichtfeld",preview:"Berichtsvorschau",excel:"Excel exportieren",print:"Drucken / PDF",saveLayout:"Mein Layout speichern",saved:"Layout gespeichert",noData:"Keine Daten für den gewählten Zeitraum",date:"Datum",weekday:"Wochentag",driver:"Fahrer",start:"Arbeitsbeginn",end:"Arbeitsende",workTime:"Arbeitszeit",breakTime:"Pause",net:"Nettozeit",truck:"Fahrzeug",trailer:"Auflieger",odoStart:"Kilometerstand Start",odoEnd:"Kilometerstand Ende",km:"Kilometer",startPlace:"Startort",endPlace:"Endort",loads:"Beladungen",unloads:"Entladungen",pallets:"Paletten",emptyPallets:"Leere Paletten",places:"Vorgangsorte",opTimes:"Vorgangszeiten",notes:"Notizen",operation:"Vorgangstyp",operationPlace:"Vorgangsort",operationStart:"Vorgang Start",operationEnd:"Vorgang Ende",daysCount:"Tage",totalNet:"Nettozeit gesamt",totalKm:"Kilometer gesamt",totalPallets:"Paletten gesamt"},
no:{title:"Rapporter / Eksport",back:"← Start",scope:"Rapportperiode",day:"Én dag",month:"Måned",type:"Rapporttype",summary:"Dagsoversikt",details:"Operasjonsdetaljer",fields:"Velg kolonner",required:"obligatorisk",preview:"Forhåndsvisning",excel:"Eksporter Excel",print:"Skriv ut / PDF",saveLayout:"Husk mitt oppsett",saved:"Oppsett lagret",noData:"Ingen data for valgt periode",date:"Dato",weekday:"Ukedag",driver:"Sjåfør",start:"Arbeidsstart",end:"Arbeidsslutt",workTime:"Arbeidstid",breakTime:"Pause",net:"Netto tid",truck:"Kjøretøy",trailer:"Tilhenger",odoStart:"Kilometerstand start",odoEnd:"Kilometerstand slutt",km:"Kilometer",startPlace:"Startsted",endPlace:"Sluttsted",loads:"Lastinger",unloads:"Lossinger",pallets:"Antall paller",emptyPallets:"Tomme paller",places:"Operasjonssteder",opTimes:"Operasjonstider",notes:"Notater",operation:"Operasjonstype",operationPlace:"Operasjonssted",operationStart:"Operasjon start",operationEnd:"Operasjon slutt",daysCount:"Dager",totalNet:"Total netto tid",totalKm:"Totale km",totalPallets:"Totalt paller"}
};
const t=()=>TXT[lang()]||TXT.pl;
const SUMMARY_FIELDS=["date","weekday","driver","start","end","workTime","breakTime","net","truck","trailer","odoStart","odoEnd","km","startPlace","endPlace","loads","unloads","pallets","emptyPallets","places","opTimes","notes"];
const DETAIL_FIELDS=["date","weekday","driver","truck","trailer","operation","operationPlace","operationStart","operationEnd","pallets","emptyPallets","notes"];
const DEFAULT_SUMMARY=["date","start","end","net","truck","trailer","km","pallets"];
const DEFAULT_DETAILS=["date","truck","trailer","operation","operationPlace","operationStart","operationEnd","pallets","emptyPallets"];
let state={days:[],ops:[],rows:[],columns:[]};

function minutesText(value){const m=Math.max(0,Number(value)||0);return `${Math.floor(m/60)}:${String(m%60).padStart(2,"0")}`;}
function timeToMinutes(v){if(!v||!/^[0-2]\d:[0-5]\d$/.test(v))return 0;const [h,m]=v.split(":").map(Number);return h*60+m;}
function calcWork(day){if(day.netMinutes!=null)return Number(day.netMinutes)||0;if(!day.finalStartTime||!day.finalEndTime)return 0;let n=timeToMinutes(day.finalEndTime)-timeToMinutes(day.finalStartTime);if(n<0)n+=1440;return Math.max(0,n-(Number(day.breakMinutes)||0));}
function locale(){return ({pl:"pl-PL",en:"en-GB",de:"de-DE",no:"nb-NO"})[lang()]||"pl-PL";}
function weekday(id){try{return new Intl.DateTimeFormat(locale(),{weekday:"short"}).format(new Date(`${id}T12:00:00`));}catch{return "";}}
function dayOps(id){return state.ops.filter(o=>(o.workdayId||o.date)===id).sort((a,b)=>String(a.startTime||"").localeCompare(String(b.startTime||"")));}
function fieldLabel(key){return t()[key]||key;}
function selectedFields(){return $$("#reportFields input[data-field]:checked").map(x=>x.dataset.field);}
function savedLayout(type){try{const raw=JSON.parse(localStorage.getItem("rumcajs-report-layout-v1")||"{}");return Array.isArray(raw[type])?raw[type]:null;}catch{return null;}}
function saveLayout(){const type=$("#reportType").value;let raw={};try{raw=JSON.parse(localStorage.getItem("rumcajs-report-layout-v1")||"{}");}catch{}raw[type]=selectedFields();localStorage.setItem("rumcajs-report-layout-v1",JSON.stringify(raw));const b=$("#saveReportLayout");const old=b.textContent;b.textContent=t().saved;setTimeout(()=>b.textContent=old,1400);}
function addStyle(){if($("#reportExportStyle"))return;const s=document.createElement("style");s.id="reportExportStyle";s.textContent=`.report-page{display:grid;gap:12px}.report-controls{display:grid;gap:10px}.report-two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.report-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.report-field{display:flex;align-items:center;gap:8px;border:1px solid var(--line);border-radius:11px;padding:9px;background:var(--card);font-size:.82rem}.report-field input{width:auto;margin:0}.report-required{color:var(--muted);font-size:.68rem}.report-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.report-actions .excel{background:#15803d;color:#fff;border-color:#166534}.report-actions .print{background:#2563eb;color:#fff;border-color:#1d4ed8}.report-preview{overflow:auto;border:1px solid var(--line);border-radius:13px;background:var(--card)}.report-preview table{border-collapse:collapse;width:100%;min-width:620px;font-size:.76rem}.report-preview th,.report-preview td{padding:7px 8px;border-bottom:1px solid var(--line);border-right:1px solid var(--line);text-align:left;vertical-align:top;white-space:nowrap}.report-preview th{position:sticky;top:0;background:#f1f5f9;color:#0f172a}.report-totals{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.report-total{padding:9px;border:1px solid var(--line);border-radius:11px;background:var(--card)}.report-total span{display:block;font-size:.72rem;color:var(--muted)}.report-total strong{display:block;margin-top:2px}@media(max-width:390px){.report-fields{grid-template-columns:1fr}.report-actions{grid-template-columns:1fr}.report-two{grid-template-columns:1fr}}`;document.head.appendChild(s);}
function ensureView(){let v=$("#view-reports");if(!v){v=document.createElement("section");v.id="view-reports";v.className="view";document.querySelector("main")?.appendChild(v);}return v;}
function renderFields(){const type=$("#reportType").value,fields=type==="summary"?SUMMARY_FIELDS:DETAIL_FIELDS,saved=savedLayout(type),defaults=saved||(type==="summary"?DEFAULT_SUMMARY:DEFAULT_DETAILS),box=$("#reportFields");box.innerHTML=fields.map(key=>`<label class="report-field"><input type="checkbox" data-field="${key}" ${key==="date"||defaults.includes(key)?"checked":""} ${key==="date"?"disabled":""}><span>${esc(fieldLabel(key))}${key==="date"?` <small class="report-required">(${t().required})</small>`:""}</span></label>`).join("");box.querySelectorAll("input").forEach(x=>x.onchange=buildPreview);}
function updateScopeInput(){const scope=$("#reportScope").value,input=$("#reportDate");input.type=scope==="day"?"date":"month";const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`;input.value=scope==="day"?today:today.slice(0,7);}
function inScope(id){const scope=$("#reportScope").value,val=$("#reportDate").value;return scope==="day"?id===val:id?.slice(0,7)===val;}
function summaryValue(day,key){const ops=dayOps(day.id),loads=ops.filter(o=>o.type==="load"),unloads=ops.filter(o=>o.type==="unload"),pallets=ops.reduce((s,o)=>s+(Number(o.pallets)||0),0),empty=ops.reduce((s,o)=>s+(Number(o.emptyPallets)||0),0),km=day.startOdometer!=null&&day.endOdometer>=day.startOdometer?day.endOdometer-day.startOdometer:"";const values={date:day.id,weekday:weekday(day.id),driver:day.driverName||"",start:day.finalStartTime||"",end:day.finalEndTime||"",workTime:day.finalStartTime&&day.finalEndTime?minutesText(timeToMinutes(day.finalEndTime)-timeToMinutes(day.finalStartTime)+(timeToMinutes(day.finalEndTime)<timeToMinutes(day.finalStartTime)?1440:0)):"",breakTime:Number(day.breakMinutes)||0,net:minutesText(calcWork(day)),truck:day.truckId||"",trailer:day.trailerId||day.trailerNumber||"Solo",odoStart:day.startOdometer??"",odoEnd:day.endOdometer??"",km,startPlace:day.startAddress||day.startPosition?.formattedAddress||"",endPlace:day.endAddress||day.endPosition?.formattedAddress||"",loads:loads.length,unloads:unloads.length,pallets,emptyPallets:empty,places:ops.map(o=>o.place||o.storeName).filter(Boolean).join(" | "),opTimes:ops.map(o=>`${o.startTime||"—"}-${o.endTime||"…"} ${o.place||o.storeName||""}`).join(" | "),notes:[day.notes||day.dayNote,...ops.map(o=>o.notes)].filter(Boolean).join(" | ")};return values[key]??"";}
function detailValue(o,day,key){const values={date:day?.id||o.workdayId||o.date||"",weekday:weekday(day?.id||o.workdayId||o.date||""),driver:day?.driverName||"",truck:day?.truckId||"",trailer:day?.trailerId||day?.trailerNumber||"Solo",operation:o.type==="load"?t().loads:t().unloads,operationPlace:o.place||o.storeName||"",operationStart:o.startTime||"",operationEnd:o.endTime||"",pallets:o.pallets??"",emptyPallets:o.emptyPallets??"",notes:o.notes||""};return values[key]??"";}
function buildRows(){const type=$("#reportType").value,days=state.days.filter(d=>inScope(d.id)).sort((a,b)=>String(a.id).localeCompare(String(b.id)));if(type==="summary")return days.map(day=>Object.fromEntries(selectedFields().map(k=>[k,summaryValue(day,k)])));const rows=[];for(const day of days)for(const o of dayOps(day.id))rows.push(Object.fromEntries(selectedFields().map(k=>[k,detailValue(o,day,k)])));return rows;}
function totalsHTML(){const days=state.days.filter(d=>inScope(d.id)),ops=state.ops.filter(o=>inScope(o.workdayId||o.date)),net=days.reduce((s,d)=>s+calcWork(d),0),km=days.reduce((s,d)=>s+(d.startOdometer!=null&&d.endOdometer>=d.startOdometer?d.endOdometer-d.startOdometer:0),0),pallets=ops.reduce((s,o)=>s+(Number(o.pallets)||0),0);return `<div class="report-totals"><div class="report-total"><span>${t().daysCount}</span><strong>${days.length}</strong></div><div class="report-total"><span>${t().totalNet}</span><strong>${minutesText(net)}</strong></div><div class="report-total"><span>${t().totalKm}</span><strong>${km} km</strong></div><div class="report-total"><span>${t().totalPallets}</span><strong>${pallets}</strong></div></div>`;}
function tableHTML(rows,cols,forPrint=false){if(!rows.length)return `<p class="muted" style="padding:12px">${t().noData}</p>`;return `<table${forPrint?' class="print-table"':''}><thead><tr>${cols.map(k=>`<th>${esc(fieldLabel(k))}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(k=>`<td>${esc(r[k])}</td>`).join("")}</tr>`).join("")}</tbody></table>`;}
function buildPreview(){if(!$("#reportFields"))return;state.columns=selectedFields();state.rows=buildRows();$("#reportTotals").innerHTML=totalsHTML();$("#reportPreview").innerHTML=tableHTML(state.rows,state.columns);}
function excelExport(){buildPreview();if(!state.rows.length)return;const title=t().title,table=tableHTML(state.rows,state.columns,true),html=`<!doctype html><html><head><meta charset="utf-8"><style>table{border-collapse:collapse}th,td{border:1px solid #999;padding:6px}th{font-weight:bold;background:#eee}</style></head><body><h2>${esc(title)}</h2>${table}</body></html>`,blob=new Blob(["\ufeff",html],{type:"application/vnd.ms-excel;charset=utf-8"}),a=document.createElement("a"),scope=$("#reportDate").value;a.href=URL.createObjectURL(blob);a.download=`Rumcajs_Dziennik_${scope}_${$("#reportType").value}.xls`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},1000);}
function printReport(){buildPreview();if(!state.rows.length)return;const w=window.open("","_blank");if(!w)return;const scope=$("#reportDate").value;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(t().title)} ${esc(scope)}</title><style>@page{size:landscape;margin:10mm}body{font-family:Arial,sans-serif;color:#111}h1{font-size:18px}p{font-size:12px}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid #777;padding:4px;text-align:left;vertical-align:top}th{background:#eee}</style></head><body><h1>${esc(t().title)} — ${esc(scope)}</h1>${tableHTML(state.rows,state.columns,true)}<script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close();}
async function render(){addStyle();const v=ensureView();v.innerHTML=`<div class="module-head"><button class="module-back" type="button">${t().back}</button><div><h2>${t().title}</h2></div></div><div class="report-page"><section class="card report-controls"><div class="report-two"><label>${t().scope}<select id="reportScope"><option value="day">${t().day}</option><option value="month">${t().month}</option></select></label><label>${t().type}<select id="reportType"><option value="summary">${t().summary}</option><option value="details">${t().details}</option></select></label></div><label><span id="reportDateLabel">${t().day}</span><input id="reportDate" type="date"></label></section><section class="card"><h3>${t().fields}</h3><div id="reportFields" class="report-fields"></div><button id="saveReportLayout" class="wide" type="button">${t().saveLayout}</button></section><div id="reportTotals"></div><section class="card"><h3>${t().preview}</h3><div id="reportPreview" class="report-preview"></div></section><div class="report-actions"><button id="reportPreviewButton" type="button">${t().preview}</button><button id="reportExcel" class="excel" type="button">${t().excel}</button><button id="reportPrint" class="print" type="button">${t().print}</button></div></div>`;state.days=await getAll(STORES.workdays);state.ops=await getAll(STORES.operations);updateScopeInput();renderFields();buildPreview();$("#reportScope").onchange=()=>{updateScopeInput();$("#reportDateLabel").textContent=$("#reportScope").value==="day"?t().day:t().month;buildPreview();};$("#reportDate").onchange=buildPreview;$("#reportType").onchange=()=>{renderFields();buildPreview();};$("#saveReportLayout").onclick=saveLayout;$("#reportPreviewButton").onclick=buildPreview;$("#reportExcel").onclick=excelExport;$("#reportPrint").onclick=printReport;}
function boot(){document.addEventListener("dashboard-view-opened",e=>{if(e.detail==="reports")render().catch(console.error);});}
boot();
