const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const WIDTH={date:72,weekday:58,driver:96,start:54,end:54,workTime:58,breakTime:50,net:54,truck:62,trailer:62,odoStart:68,odoEnd:68,km:46,startPlace:120,endPlace:120,loads:48,unloads:48,pallets:48,emptyPallets:54,places:120,opTimes:118,notes:132,operation:64,operationPlace:116,operationStart:56,operationEnd:56};
function addStyle(){if($("#reportsCompactStyle"))return;const s=document.createElement("style");s.id="reportsCompactStyle";s.textContent=`#view-reports .module-head{margin-bottom:7px!important}#view-reports .report-page{gap:7px!important}#view-reports .card{padding:8px!important;border-radius:10px!important}#view-reports .report-controls{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:5px!important}#view-reports .report-two{display:contents!important}#view-reports .report-controls label{font-size:.7rem!important;min-width:0}#view-reports .report-controls select,#view-reports .report-controls input{min-height:32px!important;height:32px!important;padding:3px 5px!important;margin-top:2px!important;font-size:.72rem!important}#view-reports h3{font-size:.84rem!important;margin:0 0 5px!important}#view-reports .report-fields{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:3px!important}#view-reports .report-field{min-height:27px!important;padding:3px 5px!important;border-radius:7px!important;gap:4px!important;font-size:.68rem!important;line-height:1.05!important}#view-reports .report-field input{width:14px!important;height:14px!important;margin:0!important;flex:0 0 14px}#view-reports .report-required{font-size:.55rem!important}#view-reports #saveReportLayout{min-height:31px!important;height:31px!important;padding:3px 6px!important;margin-top:5px!important;font-size:.68rem!important}#view-reports .report-totals{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:3px!important}#view-reports .report-total{padding:4px 5px!important;border-radius:7px!important;min-width:0}#view-reports .report-total span{font-size:.56rem!important;line-height:1!important}#view-reports .report-total strong{font-size:.76rem!important;margin-top:1px!important;white-space:nowrap}#view-reports .report-preview{border-radius:7px!important;max-height:54vh!important}#view-reports .report-preview table{min-width:0!important;width:max-content!important;font-size:.62rem!important;line-height:1!important}#view-reports .report-preview th,#view-reports .report-preview td{padding:2px 3px!important;white-space:nowrap!important;max-width:130px!important;overflow:hidden!important;text-overflow:ellipsis!important}#view-reports .report-actions{grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:4px!important}#view-reports .report-actions button{min-height:34px!important;height:34px!important;padding:3px 5px!important;font-size:.68rem!important}@media(max-width:360px){#view-reports .report-controls{grid-template-columns:1fr 1fr!important}#view-reports .report-controls>label:last-child{grid-column:1/-1}#view-reports .report-totals{grid-template-columns:repeat(2,1fr)!important}}`;document.head.appendChild(s);}
function selected(){return $$("#reportFields input[data-field]:checked").map(x=>x.dataset.field);}
function compactTable(){const src=$("#reportPreview table");if(!src)return null;const table=src.cloneNode(true),cols=selected();table.querySelector("colgroup")?.remove();const cg=document.createElement("colgroup");cols.forEach(k=>{const c=document.createElement("col");c.setAttribute("width",String(WIDTH[k]||72));c.style.width=`${WIDTH[k]||72}px`;cg.appendChild(c);});table.insertBefore(cg,table.firstChild);return table;}
function scopeName(){return $("#reportDate")?.value||"raport";}
function prepare(){try{$("#reportPreviewButton")?.onclick?.();}catch{}return compactTable();}
function exportExcel(){const table=prepare();if(!table)return;const html=`<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;font-size:8pt;margin:4px}h2{font-size:10pt;margin:0 0 4px}table{border-collapse:collapse;table-layout:fixed;width:auto}th,td{border:1px solid #aaa;padding:1px 2px;font-size:7pt;line-height:1.05;vertical-align:top;white-space:normal;word-wrap:break-word}th{font-weight:bold;background:#eee}</style></head><body><h2>Rumcajs Work Log — ${esc(scopeName())}</h2>${table.outerHTML}</body></html>`;const blob=new Blob(["\ufeff",html],{type:"application/vnd.ms-excel;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`Rumcajs_Dziennik_${scopeName()}.xls`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},800);}
function printCompact(){const table=prepare();if(!table)return;const w=window.open("","_blank");if(!w)return;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Rumcajs Work Log ${esc(scopeName())}</title><style>@page{size:landscape;margin:6mm}body{font-family:Arial,sans-serif;color:#111;margin:0}h1{font-size:12px;margin:0 0 4px}table{border-collapse:collapse;table-layout:fixed;width:auto;font-size:7px}th,td{border:1px solid #888;padding:1px 2px;line-height:1.05;vertical-align:top;white-space:normal;word-wrap:break-word}th{background:#eee}</style></head><body><h1>Rumcajs Work Log — ${esc(scopeName())}</h1>${table.outerHTML}<script>window.onload=()=>setTimeout(()=>window.print(),200)<\/script></body></html>`);w.document.close();}
document.addEventListener("click",e=>{const b=e.target.closest("#reportExcel,#reportPrint");if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(b.id==="reportExcel")exportExcel();else printCompact();},true);
document.addEventListener("dashboard-view-opened",e=>{if(e.detail==="reports")setTimeout(addStyle,0);});addStyle();