import { get, STORES } from "./db/indexeddb.js";
import { getDay, saveDay } from "./modules/workdays.js";
import { getCurrentPosition } from "./modules/gps.js";
import { reverseGeocode } from "./modules/reverse-geocode.js";
import { dateId, clock } from "./modules/time.js";

const $=s=>document.querySelector(s);
let bypassStart=false,bypassStop=false;
const txt={pl:{drop:"Odstaw naczepę",attach:"Podepnij naczepę",change:"Zmień zestaw",trailer:"Numer naczepy / przyczepy",odo:"Stan licznika (km)",note:"Notatka (opcjonalnie)",saved:"Zdarzenie zapisane",startOdo:"Stan licznika na rozpoczęcie dnia",endOdo:"Stan licznika na zakończenie dnia",lower:"Nowy stan licznika jest niższy od poprzedniego. Zapisać mimo to?",none:"Brak podpiętej naczepy.",address:"Ustalam adres…"},en:{drop:"Drop trailer",attach:"Attach trailer",change:"Change combination",trailer:"Trailer registration",odo:"Odometer (km)",note:"Note (optional)",saved:"Event saved",startOdo:"Start odometer",endOdo:"End odometer",lower:"New odometer is lower than previous. Save anyway?",none:"No trailer attached.",address:"Finding address…"},de:{drop:"Anhänger abstellen",attach:"Anhänger ankuppeln",change:"Gespann wechseln",trailer:"Anhängerkennzeichen",odo:"Kilometerstand",note:"Notiz (optional)",saved:"Ereignis gespeichert",startOdo:"Kilometerstand bei Arbeitsbeginn",endOdo:"Kilometerstand bei Arbeitsende",lower:"Neuer Kilometerstand ist niedriger. Trotzdem speichern?",none:"Kein Anhänger angekuppelt.",address:"Adresse wird ermittelt…"},no:{drop:"Sett fra henger",attach:"Koble til henger",change:"Bytt vogntog",trailer:"Registreringsnummer henger",odo:"Kilometerstand",note:"Notat (valgfritt)",saved:"Hendelse lagret",startOdo:"Kilometerstand ved start",endOdo:"Kilometerstand ved slutt",lower:"Ny kilometerstand er lavere. Lagre likevel?",none:"Ingen henger tilkoblet.",address:"Finner adresse…"}};
function t(){return txt[document.documentElement.lang]||txt.pl;}
function toast(m){const b=$("#toast");if(!b)return;b.textContent=m;b.classList.remove("hidden");setTimeout(()=>b.classList.add("hidden"),2600);}
async function settings(){return await get(STORES.settings,"main")||{};}
async function isUniversal(){return (await settings()).workProfile==="universal";}
async function askOdometer(label,day){if(!(await isUniversal()))return null;const raw=prompt(label,day?.lastOdometer??day?.startOdometer??"");if(raw===null)return false;const value=Number(String(raw).replace(/\s/g,""));if(!Number.isFinite(value)||value<0)return false;const prev=Number(day?.lastOdometer);if(Number.isFinite(prev)&&value<prev&&!confirm(t().lower))return false;return value;}
async function locate(){try{const p=await getCurrentPosition();const a=await reverseGeocode(p,document.documentElement.lang||"pl");return{position:p,address:a.formattedAddress};}catch(e){console.error(e);return{position:null,address:null};}}
function ensureButtons(){const card=$("#vehicleDayCard");if(!card||$("#trailerEventActions"))return;const box=document.createElement("div");box.id="trailerEventActions";box.className="trailer-event-actions";box.innerHTML=`<button type="button" data-action="drop">${t().drop}</button><button type="button" data-action="attach">${t().attach}</button><button type="button" data-action="change">${t().change}</button>`;card.appendChild(box);box.querySelectorAll("button").forEach(b=>b.onclick=()=>handleEvent(b.dataset.action));}
async function handleEvent(type){const id=dateId(),day=await getDay(id);if(!day?.finalStartTime||day?.finalEndTime)return;let truck=day.truckId||"",trailer=day.trailerId||"";
 if(type==="drop"&&!trailer)return toast(t().none);
 if(type==="attach"){const v=prompt(t().trailer,"");if(v===null||!v.trim())return;trailer=v.trim().toUpperCase();}
 if(type==="change"){const nt=prompt("Numer rejestracyjny samochodu",truck);if(nt===null||!nt.trim())return;const nr=prompt(t().trailer,trailer);if(nr===null)return;truck=nt.trim().toUpperCase();trailer=nr.trim().toUpperCase();}
 const odo=await askOdometer(t().odo,day);if(odo===false)return;const note=prompt(t().note,"")||"";toast(t().address);const loc=await locate();const events=[...(day.trailerEvents||[])];events.push({id:`${Date.now()}`,type,time:clock(),truckBefore:day.truckId||"",truckAfter:truck,trailerBefore:day.trailerId||"",trailerAfter:type==="drop"?"":trailer,odometer:odo===null?null:odo,address:loc.address,position:loc.position,note,createdAt:Date.now()});
 await saveDay({...day,id,date:id,truckId:truck,trailerId:type==="drop"?"":trailer,trailerEvents:events,lastOdometer:odo===null?day.lastOdometer:odo});toast(t().saved);setTimeout(()=>location.reload(),250);}
async function guardStart(e){if(bypassStart||!(await isUniversal()))return;const day=await getDay(dateId());if(day?.finalStartTime||day?.startOdometer!=null)return;e.preventDefault();e.stopImmediatePropagation();const odo=await askOdometer(t().startOdo,day);if(odo===false)return;await saveDay({...day,id:dateId(),date:dateId(),dayType:day?.dayType||"work",startOdometer:odo,lastOdometer:odo});bypassStart=true;$("#startWorkButton")?.click();setTimeout(()=>bypassStart=false,0);}
async function guardStop(e){if(bypassStop||!(await isUniversal()))return;const day=await getDay(dateId());if(!day?.finalStartTime||day?.finalEndTime||day?.endOdometer!=null)return;e.preventDefault();e.stopImmediatePropagation();const odo=await askOdometer(t().endOdo,day);if(odo===false)return;await saveDay({...day,endOdometer:odo,lastOdometer:odo});bypassStop=true;$("#stopWorkButton")?.click();setTimeout(()=>bypassStop=false,0);}
function renderHistory(){const card=$("#vehicleDayCard");if(!card)return;getDay(dateId()).then(day=>{const old=$("#trailerEventHistory");if(old)old.remove();const events=day?.trailerEvents||[];if(!events.length)return;const box=document.createElement("div");box.id="trailerEventHistory";box.className="trailer-event-history";box.innerHTML=events.slice().reverse().map(e=>`<div><b>${e.time} — ${e.type==="drop"?t().drop:e.type==="attach"?t().attach:t().change}</b><span>${e.trailerBefore||"Solo"} → ${e.trailerAfter||"Solo"}${e.odometer!=null?` • ${e.odometer} km`:""}</span>${e.address?`<small>${e.address}</small>`:""}</div>`).join("");card.appendChild(box);});}
function boot(){ensureButtons();renderHistory();$("#startWorkButton")?.addEventListener("click",guardStart,true);$("#stopWorkButton")?.addEventListener("click",guardStop,true);new MutationObserver(()=>{ensureButtons();renderHistory();}).observe($("#view-home"),{childList:true,subtree:true});}
boot();