import { get, STORES } from "./db/indexeddb.js";
import { getDay, saveDay } from "./modules/workdays.js";
import { getCurrentPosition } from "./modules/gps.js";
import { reverseGeocode } from "./modules/reverse-geocode.js";
import { findNearestSavedPlace, savePlace, markPlaceUsed } from "./modules/places.js";
import { dateId, clock } from "./modules/time.js";

const $=s=>document.querySelector(s);
let currentLocation=null;
const txt={pl:{drop:"Odstaw naczepę",attach:"Podepnij / zmień naczepę",truckChange:"Zmień ciągnik",change:"Zmień cały zestaw",truck:"Numer rejestracyjny samochodu",trailer:"Numer naczepy / przyczepy",odo:"Stan licznika (km)",note:"Notatka (opcjonalnie)",place:"Miejsce / własna nazwa",address:"Adres",gps:"Ustal przez GPS",gpsBusy:"Ustalam lokalizację…",gpsDone:"Lokalizacja ustalona",savePlace:"Zapamiętaj tę nazwę dla tego miejsca",save:"Zapisz",cancel:"Anuluj",saved:"Zdarzenie zapisane",none:"Brak podpiętej naczepy.",noDay:"Najpierw rozpocznij dzień pracy.",lower:"Nowy stan licznika jest niższy od poprzedniego. Zapisać mimo to?"},en:{drop:"Drop trailer",attach:"Attach / change trailer",truckChange:"Change truck",change:"Change combination",truck:"Vehicle registration",trailer:"Trailer registration",odo:"Odometer (km)",note:"Note (optional)",place:"Place / custom name",address:"Address",gps:"Use GPS",gpsBusy:"Finding location…",gpsDone:"Location found",savePlace:"Remember this name for this place",save:"Save",cancel:"Cancel",saved:"Event saved",none:"No trailer attached.",noDay:"Start the workday first.",lower:"New odometer is lower than previous. Save anyway?"},de:{drop:"Anhänger abstellen",attach:"Anhänger ankuppeln / wechseln",truckChange:"Fahrzeug wechseln",change:"Gespann wechseln",truck:"Fahrzeugkennzeichen",trailer:"Anhängerkennzeichen",odo:"Kilometerstand",note:"Notiz (optional)",place:"Ort / eigener Name",address:"Adresse",gps:"Per GPS bestimmen",gpsBusy:"Standort wird ermittelt…",gpsDone:"Standort ermittelt",savePlace:"Diesen Namen für diesen Ort speichern",save:"Speichern",cancel:"Abbrechen",saved:"Ereignis gespeichert",none:"Kein Anhänger angekuppelt.",noDay:"Starten Sie zuerst den Arbeitstag.",lower:"Neuer Kilometerstand ist niedriger. Trotzdem speichern?"},no:{drop:"Sett fra henger",attach:"Koble til / bytt henger",truckChange:"Bytt bil",change:"Bytt vogntog",truck:"Registreringsnummer bil",trailer:"Registreringsnummer henger",odo:"Kilometerstand",note:"Notat (valgfritt)",place:"Sted / eget navn",address:"Adresse",gps:"Finn med GPS",gpsBusy:"Finner posisjon…",gpsDone:"Posisjon funnet",savePlace:"Husk dette navnet for stedet",save:"Lagre",cancel:"Avbryt",saved:"Hendelse lagret",none:"Ingen henger tilkoblet.",noDay:"Start arbeidsdagen først.",lower:"Ny kilometerstand er lavere. Lagre likevel?"}};
function t(){return txt[document.documentElement.lang||"pl"]||txt.pl;}
function toast(m){const b=$("#toast");if(!b)return;b.textContent=m;b.classList.remove("hidden");clearTimeout(toast.timer);toast.timer=setTimeout(()=>b.classList.add("hidden"),2800);}
async function settings(){return await get(STORES.settings,"main")||{};}
async function isUniversal(){return (await settings()).workProfile==="universal";}
async function activeDay(){let day=await getDay(dateId());if(!day?.finalStartTime)return null;if(day.finalEndTime){day=await saveDay({...day,id:dateId(),date:dateId(),finalEndTime:null,detectedEndTime:null,endPosition:null,endAddress:null,endOdometer:null});}return day;}
function ensureModal(){if($("#trailerEventModal"))return;const style=document.createElement("style");style.textContent=`.trailer-event-modal{position:fixed;inset:0;z-index:1400;background:rgba(0,0,0,.62);display:flex;align-items:center;justify-content:center;padding:16px}.trailer-event-modal.hidden{display:none}.trailer-event-dialog{width:min(100%,500px);max-height:92vh;overflow:auto;background:var(--card);border-radius:18px;padding:18px;box-shadow:0 20px 60px rgba(0,0,0,.4)}.trailer-event-dialog label{display:block;margin-top:12px}.trailer-event-dialog input,.trailer-event-dialog textarea{width:100%;box-sizing:border-box}.trailer-location-row{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:end}.trailer-check{display:flex!important;gap:8px;align-items:center}.trailer-check input{width:auto!important}.trailer-event-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}`;document.head.appendChild(style);const modal=document.createElement("div");modal.id="trailerEventModal";modal.className="trailer-event-modal hidden";document.body.appendChild(modal);}
function ensureButtons(){const card=$("#vehicleDayCard");if(!card)return;let box=$("#trailerEventActions");if(!box){box=document.createElement("div");box.id="trailerEventActions";box.className="trailer-event-actions";card.appendChild(box);}box.innerHTML=`<button type="button" data-trailer-action="drop">${t().drop}</button><button type="button" data-trailer-action="attach">${t().attach}</button><button type="button" data-trailer-action="truck">${t().truckChange}</button><button type="button" data-trailer-action="change">${t().change}</button>`;}
async function openForm(type){const day=await activeDay();if(!day)return toast(t().noDay);if(type==="drop"&&!day.trailerId&&!day.trailerNumber)return toast(t().none);ensureModal();currentLocation=null;const universal=await isUniversal();const showTruck=type==="truck"||type==="change";const showTrailer=type!=="truck";const title=type==="drop"?t().drop:type==="attach"?t().attach:type==="truck"?t().truckChange:t().change;const trailerValue=type==="attach"?"":(day.trailerId||day.trailerNumber||"");const modal=$("#trailerEventModal");modal.innerHTML=`<div class="trailer-event-dialog"><h2>${title}</h2>${showTruck?`<label>${t().truck}<input id="eventTruck" maxlength="30" value="${day.truckId||""}"></label>`:""}${showTrailer?`<label>${t().trailer}<input id="eventTrailer" maxlength="30" value="${trailerValue}" ${type==="drop"?"readonly":""}></label>`:""}${universal?`<label>${t().odo}<input id="eventOdometer" type="number" min="0" inputmode="numeric" value="${day.lastOdometer??day.startOdometer??""}"></label>`:""}<div class="trailer-location-row"><label>${t().place}<input id="eventPlaceName" maxlength="80"></label><button id="eventGps" type="button">${t().gps}</button></div><label>${t().address}<input id="eventAddress" maxlength="180"></label><label class="trailer-check"><input id="eventRememberPlace" type="checkbox"><span>${t().savePlace}</span></label><label>${t().note}<textarea id="eventNote" rows="3"></textarea></label><div class="button-row"><button id="eventSave" class="primary" type="button">${t().save}</button><button id="eventCancel" type="button">${t().cancel}</button></div></div>`;modal.classList.remove("hidden");$("#eventCancel").onclick=()=>modal.classList.add("hidden");$("#eventGps").onclick=detectLocation;$("#eventSave").onclick=()=>saveEvent(type,day);modal.onclick=e=>{if(e.target===modal)modal.classList.add("hidden");};}
async function detectLocation(){const b=$("#eventGps");if(!b||b.disabled)return;b.disabled=true;b.textContent=t().gpsBusy;try{const p=await getCurrentPosition();const s=await settings();const nearest=await findNearestSavedPlace(p,Number(s.gpsRadius||150));if(nearest){const used=await markPlaceUsed(nearest.place);currentLocation={position:p,address:used.address||used.name,placeName:used.name,placeId:used.id};$("#eventPlaceName").value=used.name;$("#eventAddress").value=used.address||"";}else{const a=await reverseGeocode(p,document.documentElement.lang||"pl");currentLocation={position:p,address:a.formattedAddress,locality:a.locality,countryCode:a.countryCode};$("#eventAddress").value=a.formattedAddress;}toast(t().gpsDone);}catch(e){console.error(e);toast(e.message||"GPS error");}finally{b.disabled=false;b.textContent=t().gps;}}
async function saveEvent(type,day){let truck=day.truckId||"",trailer=day.trailerId||day.trailerNumber||"";if(type==="truck"||type==="change"){truck=$("#eventTruck").value.trim().toUpperCase();if(!truck)return $("#eventTruck").focus();}if(type==="attach"||type==="change"){trailer=$("#eventTrailer").value.trim().toUpperCase();if(!trailer)return $("#eventTrailer").focus();}if(type==="drop")trailer="";let odo=null;if(await isUniversal()){const raw=$("#eventOdometer").value.trim();if(raw==="")return $("#eventOdometer").focus();odo=Number(raw.replace(/\s/g,""));if(!Number.isFinite(odo)||odo<0)return $("#eventOdometer").focus();const prev=Number(day.lastOdometer);if(Number.isFinite(prev)&&odo<prev&&!confirm(t().lower))return;}const placeName=$("#eventPlaceName").value.trim();const typedAddress=$("#eventAddress").value.trim();const address=typedAddress||currentLocation?.address||null;const note=$("#eventNote").value.trim();if($("#eventRememberPlace").checked&&placeName&&currentLocation?.position){try{await savePlace({name:placeName,address:address||placeName,position:currentLocation.position,locality:currentLocation.locality||null,countryCode:currentLocation.countryCode||null});}catch(e){console.error(e);}}const events=[...(day.trailerEvents||[])];events.push({id:String(Date.now()),type,time:clock(),truckBefore:day.truckId||"",truckAfter:truck,trailerBefore:day.trailerId||day.trailerNumber||"",trailerAfter:trailer,odometer:odo,address,placeName:placeName||null,position:currentLocation?.position||null,note,createdAt:Date.now()});await saveDay({...day,id:dateId(),date:dateId(),truckId:truck,trailerId:trailer,trailerNumber:trailer,trailerEvents:events,lastOdometer:odo===null?day.lastOdometer:odo});$("#trailerEventModal").classList.add("hidden");toast(t().saved);document.dispatchEvent(new CustomEvent("vehicle-data-changed"));setTimeout(()=>location.reload(),180);}
function renderHistory(){getDay(dateId()).then(day=>{const card=$("#vehicleDayCard");if(!card)return;$("#trailerEventHistory")?.remove();const events=day?.trailerEvents||[];if(!events.length)return;const box=document.createElement("div");box.id="trailerEventHistory";box.className="trailer-event-history";box.innerHTML=events.slice().reverse().map(e=>`<div><b>${e.time} — ${e.type==="drop"?t().drop:e.type==="attach"?t().attach:e.type==="truck"?t().truckChange:t().change}</b><span>${e.truckBefore||"—"} / ${e.trailerBefore||"Solo"} → ${e.truckAfter||"—"} / ${e.trailerAfter||"Solo"}${e.odometer!=null?` • ${e.odometer} km`:""}</span>${e.placeName?`<small>${e.placeName}</small>`:""}${e.address?`<small>${e.address}</small>`:""}</div>`).join("");card.appendChild(box);}).catch(console.error);}
function refresh(){ensureButtons();renderHistory();}
document.addEventListener("click",event=>{const b=event.target.closest("[data-trailer-action]");if(!b)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();openForm(b.dataset.trailerAction).catch(error=>{console.error(error);toast(error.message||"Błąd");});},true);
document.addEventListener("vehicle-card-rendered",refresh);document.addEventListener("dashboard-view-opened",e=>{if(e.detail==="workday")setTimeout(refresh,0);});document.addEventListener("visibilitychange",()=>{if(!document.hidden)refresh();});ensureModal();setTimeout(refresh,300);