import { get, put, STORES } from "./db/indexeddb.js";
import { getDay } from "./modules/workdays.js";
import { dateId } from "./modules/time.js";

const $=s=>document.querySelector(s);
const KEY="transport-profile";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const lang=()=>document.documentElement.lang||"pl";
const TEXT={
 pl:{title:"Konfiguracja transportu",hint:"Typ pojazdu, zabudowy i jednostka ładunku",vehicle:"Typ pojazdu",weight:"Kategoria DMC",body:"Zabudowa samochodu",trailer:"Typ naczepy / przyczepy",unit:"Domyślna jednostka ładunku",material:"Domyślny opis ładunku (opcjonalnie)",save:"Zapisz konfigurację",saved:"Konfiguracja transportu zapisana",back:"← Start",summary:"Bieżąca konfiguracja",universal:"Moduł jest dostępny w profilu Uniwersalnym.",truck:"Ciągnik siodłowy z naczepą",rigid:"Samochód ciężarowy / solówka",rigidTrailer:"Samochód ciężarowy z przyczepą",van25:"Bus do 2,5 t",vanOver25:"Bus powyżej 2,5 t",other:"Inny",curtain:"Plandeka / firanka",box:"Furgon / skrzynia",reefer:"Chłodnia",isotherm:"Izoterma",tanker:"Cysterna do płynów",gas:"Cysterna gazowa",silo:"Silos",tipper:"Wanna / wywrotka",bdf:"BDF / kontener wymienny",flatbed:"Platforma",none:"Brak / solo",pallets:"palety",cartons:"kartony",tonnes:"tony",kg:"kg",m3:"m³",litres:"litry",pieces:"sztuki"},
 en:{title:"Transport configuration",hint:"Vehicle, body and cargo unit",vehicle:"Vehicle type",weight:"Weight category",body:"Vehicle body",trailer:"Trailer type",unit:"Default cargo unit",material:"Default cargo description (optional)",save:"Save configuration",saved:"Transport configuration saved",back:"← Home",summary:"Current configuration",universal:"This module is available in Universal profile.",truck:"Tractor and semi-trailer",rigid:"Rigid truck",rigidTrailer:"Rigid truck with trailer",van25:"Van up to 2.5 t",vanOver25:"Van over 2.5 t",other:"Other",curtain:"Curtainsider",box:"Box body",reefer:"Refrigerated",isotherm:"Insulated",tanker:"Liquid tanker",gas:"Gas tanker",silo:"Silo",tipper:"Tipper",bdf:"BDF / swap body",flatbed:"Flatbed",none:"None / solo",pallets:"pallets",cartons:"cartons",tonnes:"tonnes",kg:"kg",m3:"m³",litres:"litres",pieces:"pieces"}
};
const t=()=>TEXT[lang()]||TEXT.en;
const options=(items,current)=>items.map(([v,l])=>`<option value="${v}" ${v===current?"selected":""}>${esc(l)}</option>`).join("");
function ensureStyle(){if($("#transportProfileStyle"))return;const s=document.createElement("style");s.id="transportProfileStyle";s.textContent=`.transport-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.transport-summary{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.transport-summary div{border:1px solid var(--line);border-radius:12px;padding:9px;background:var(--card)}.transport-summary span{display:block;color:var(--muted);font-size:.75rem}.transport-summary strong{display:block;margin-top:2px}.transport-day-card{margin:8px 0;padding:9px 11px;border-radius:12px;border:1px solid var(--line);background:var(--card)}.transport-day-card small{color:var(--muted)}@media(max-width:520px){.transport-grid,.transport-summary{grid-template-columns:1fr}}`;document.head.appendChild(s);}
async function data(){return await get(STORES.appState,KEY)||{id:KEY,vehicleType:"tractor",weightClass:"over35",bodyType:"none",trailerType:"curtain",cargoUnit:"pallets",defaultMaterial:""};}
function label(map,value){return map.find(x=>x[0]===value)?.[1]||value||"—";}
function lists(){const x=t();return{
 vehicle:[["tractor",x.truck],["rigid",x.rigid],["rigid-trailer",x.rigidTrailer],["van-25",x.van25],["van-over25",x.vanOver25],["other",x.other]],
 weight:[["under25","≤ 2,5 t"],["25-35","2,5–3,5 t"],["over35","> 3,5 t"]],
 body:[["none",x.none],["curtain",x.curtain],["box",x.box],["reefer",x.reefer],["isotherm",x.isotherm],["tanker",x.tanker],["gas",x.gas],["silo",x.silo],["tipper",x.tipper],["bdf",x.bdf],["flatbed",x.flatbed],["other",x.other]],
 trailer:[["none",x.none],["curtain",x.curtain],["box",x.box],["reefer",x.reefer],["isotherm",x.isotherm],["tanker",x.tanker],["gas",x.gas],["silo",x.silo],["tipper",x.tipper],["bdf",x.bdf],["flatbed",x.flatbed],["other",x.other]],
 unit:[["pallets",x.pallets],["cartons",x.cartons],["tonnes",x.tonnes],["kg",x.kg],["m3",x.m3],["litres",x.litres],["pieces",x.pieces]]};}
async function render(){ensureStyle();let view=$("#view-transport");if(!view){view=document.createElement("section");view.id="view-transport";view.className="view";document.querySelector("main")?.appendChild(view);}const settings=await get(STORES.settings,"main")||{};const d=await data(),L=lists(),x=t();view.innerHTML=`<div class="module-head"><button class="module-back" type="button">${x.back}</button><div><small>TRANSPORT</small><h2>${x.title}</h2></div></div><article class="card">${settings.workProfile!=="universal"?`<p class="muted">${x.universal}</p>`:""}<form id="transportProfileForm"><div class="transport-grid"><label>${x.vehicle}<select id="transportVehicle">${options(L.vehicle,d.vehicleType)}</select></label><label>${x.weight}<select id="transportWeight">${options(L.weight,d.weightClass)}</select></label><label>${x.body}<select id="transportBody">${options(L.body,d.bodyType)}</select></label><label>${x.trailer}<select id="transportTrailer">${options(L.trailer,d.trailerType)}</select></label><label>${x.unit}<select id="transportUnit">${options(L.unit,d.cargoUnit)}</select></label><label>${x.material}<input id="transportMaterial" maxlength="80" value="${esc(d.defaultMaterial)}"></label></div><button class="primary wide" type="submit">${x.save}</button></form></article><article class="card"><small>${x.summary.toUpperCase()}</small><div id="transportSummary" class="transport-summary"></div></article>`;
 const draw=()=>{$("#transportSummary").innerHTML=`<div><span>${x.vehicle}</span><strong>${esc(label(L.vehicle,$("#transportVehicle").value))}</strong></div><div><span>${x.weight}</span><strong>${esc(label(L.weight,$("#transportWeight").value))}</strong></div><div><span>${x.body}</span><strong>${esc(label(L.body,$("#transportBody").value))}</strong></div><div><span>${x.trailer}</span><strong>${esc(label(L.trailer,$("#transportTrailer").value))}</strong></div><div><span>${x.unit}</span><strong>${esc(label(L.unit,$("#transportUnit").value))}</strong></div><div><span>${x.material}</span><strong>${esc($("#transportMaterial").value||"—")}</strong></div>`;};
 view.querySelectorAll("select,input").forEach(el=>el.addEventListener("input",draw));draw();
 $("#transportProfileForm").onsubmit=async e=>{e.preventDefault();await put(STORES.appState,{id:KEY,vehicleType:$("#transportVehicle").value,weightClass:$("#transportWeight").value,bodyType:$("#transportBody").value,trailerType:$("#transportTrailer").value,cargoUnit:$("#transportUnit").value,defaultMaterial:$("#transportMaterial").value.trim(),updatedAt:Date.now()});const toast=$("#toast");if(toast){toast.textContent=x.saved;toast.classList.remove("hidden");setTimeout(()=>toast.classList.add("hidden"),2200);}document.dispatchEvent(new CustomEvent("transport-profile-changed"));};}
async function renderDayCard(){const view=$("#view-workday");if(!view)return;const settings=await get(STORES.settings,"main")||{};let card=$("#transportDayCard");if(settings.workProfile!=="universal"){card?.remove();return;}const d=await data(),L=lists(),x=t();if(!card){card=document.createElement("div");card.id="transportDayCard";card.className="transport-day-card";const target=$("#workdayLiveStrip");(target?.parentElement||view).insertBefore(card,target?.nextSibling||view.firstChild);}card.innerHTML=`<small>${x.summary}</small><strong>${esc(label(L.vehicle,d.vehicleType))} • ${esc(label(L.trailer,d.trailerType))} • ${esc(label(L.unit,d.cargoUnit))}</strong>`;}
function boot(){ensureStyle();document.addEventListener("dashboard-view-opened",e=>{if(e.detail==="transport")render().catch(console.error);if(e.detail==="workday")setTimeout(()=>renderDayCard().catch(console.error),50);});document.addEventListener("transport-profile-changed",()=>renderDayCard().catch(console.error));}
boot();